// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_plan

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.AdvancedBackupSettings) != len(b.ko.Spec.AdvancedBackupSettings) {
		delta.Add("Spec.AdvancedBackupSettings", a.ko.Spec.AdvancedBackupSettings, b.ko.Spec.AdvancedBackupSettings)
	} else if len(a.ko.Spec.AdvancedBackupSettings) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.AdvancedBackupSettings, b.ko.Spec.AdvancedBackupSettings) {
			delta.Add("Spec.AdvancedBackupSettings", a.ko.Spec.AdvancedBackupSettings, b.ko.Spec.AdvancedBackupSettings)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.Rules) != len(b.ko.Spec.Rules) {
		delta.Add("Spec.Rules", a.ko.Spec.Rules, b.ko.Spec.Rules)
	} else if len(a.ko.Spec.Rules) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Rules, b.ko.Spec.Rules) {
			delta.Add("Spec.Rules", a.ko.Spec.Rules, b.ko.Spec.Rules)
		}
	}
	if len(a.ko.Spec.ScanSettings) != len(b.ko.Spec.ScanSettings) {
		delta.Add("Spec.ScanSettings", a.ko.Spec.ScanSettings, b.ko.Spec.ScanSettings)
	} else if len(a.ko.Spec.ScanSettings) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ScanSettings, b.ko.Spec.ScanSettings) {
			delta.Add("Spec.ScanSettings", a.ko.Spec.ScanSettings, b.ko.Spec.ScanSettings)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
