// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_plan

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/backup"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/backup/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/backup-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.BackupPlan{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetBackupPlanOutput
	resp, err = rm.sdkapi.GetBackupPlan(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetBackupPlan", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.BackupPlan.AdvancedBackupSettings != nil {
		f0 := []*svcapitypes.AdvancedBackupSetting{}
		for _, f0iter := range resp.BackupPlan.AdvancedBackupSettings {
			f0elem := &svcapitypes.AdvancedBackupSetting{}
			if f0iter.BackupOptions != nil {
				f0elem.BackupOptions = aws.StringMap(f0iter.BackupOptions)
			}
			if f0iter.ResourceType != nil {
				f0elem.ResourceType = f0iter.ResourceType
			}
			f0 = append(f0, f0elem)
		}
		ko.Spec.AdvancedBackupSettings = f0
	} else {
		ko.Spec.AdvancedBackupSettings = nil
	}
	if resp.BackupPlan.BackupPlanName != nil {
		ko.Spec.Name = resp.BackupPlan.BackupPlanName
	} else {
		ko.Spec.Name = nil
	}
	if resp.BackupPlan.Rules != nil {
		f2 := []*svcapitypes.RuleInput{}
		for _, f2iter := range resp.BackupPlan.Rules {
			f2elem := &svcapitypes.RuleInput{}
			if f2iter.CompletionWindowMinutes != nil {
				f2elem.CompletionWindowMinutes = f2iter.CompletionWindowMinutes
			}
			if f2iter.CopyActions != nil {
				f2elemf1 := []*svcapitypes.CopyAction{}
				for _, f2elemf1iter := range f2iter.CopyActions {
					f2elemf1elem := &svcapitypes.CopyAction{}
					if f2elemf1iter.DestinationBackupVaultArn != nil {
						f2elemf1elem.DestinationBackupVaultARN = f2elemf1iter.DestinationBackupVaultArn
					}
					if f2elemf1iter.Lifecycle != nil {
						f2elemf1elemf1 := &svcapitypes.Lifecycle{}
						if f2elemf1iter.Lifecycle.DeleteAfterDays != nil {
							f2elemf1elemf1.DeleteAfterDays = f2elemf1iter.Lifecycle.DeleteAfterDays
						}
						if f2elemf1iter.Lifecycle.DeleteAfterEvent != "" {
							f2elemf1elemf1.DeleteAfterEvent = aws.String(string(f2elemf1iter.Lifecycle.DeleteAfterEvent))
						}
						if f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays != nil {
							f2elemf1elemf1.MoveToColdStorageAfterDays = f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays
						}
						if f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
							f2elemf1elemf1.OptInToArchiveForSupportedResources = f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources
						}
						f2elemf1elem.Lifecycle = f2elemf1elemf1
					}
					f2elemf1 = append(f2elemf1, f2elemf1elem)
				}
				f2elem.CopyActions = f2elemf1
			}
			if f2iter.EnableContinuousBackup != nil {
				f2elem.EnableContinuousBackup = f2iter.EnableContinuousBackup
			}
			if f2iter.IndexActions != nil {
				f2elemf3 := []*svcapitypes.IndexAction{}
				for _, f2elemf3iter := range f2iter.IndexActions {
					f2elemf3elem := &svcapitypes.IndexAction{}
					if f2elemf3iter.ResourceTypes != nil {
						f2elemf3elem.ResourceTypes = aws.StringSlice(f2elemf3iter.ResourceTypes)
					}
					f2elemf3 = append(f2elemf3, f2elemf3elem)
				}
				f2elem.IndexActions = f2elemf3
			}
			if f2iter.Lifecycle != nil {
				f2elemf4 := &svcapitypes.Lifecycle{}
				if f2iter.Lifecycle.DeleteAfterDays != nil {
					f2elemf4.DeleteAfterDays = f2iter.Lifecycle.DeleteAfterDays
				}
				if f2iter.Lifecycle.DeleteAfterEvent != "" {
					f2elemf4.DeleteAfterEvent = aws.String(string(f2iter.Lifecycle.DeleteAfterEvent))
				}
				if f2iter.Lifecycle.MoveToColdStorageAfterDays != nil {
					f2elemf4.MoveToColdStorageAfterDays = f2iter.Lifecycle.MoveToColdStorageAfterDays
				}
				if f2iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
					f2elemf4.OptInToArchiveForSupportedResources = f2iter.Lifecycle.OptInToArchiveForSupportedResources
				}
				f2elem.Lifecycle = f2elemf4
			}
			if f2iter.RecoveryPointTags != nil {
				f2elem.RecoveryPointTags = aws.StringMap(f2iter.RecoveryPointTags)
			}
			if f2iter.RuleName != nil {
				f2elem.RuleName = f2iter.RuleName
			}
			if f2iter.ScanActions != nil {
				f2elemf8 := []*svcapitypes.ScanAction{}
				for _, f2elemf8iter := range f2iter.ScanActions {
					f2elemf8elem := &svcapitypes.ScanAction{}
					if f2elemf8iter.MalwareScanner != "" {
						f2elemf8elem.MalwareScanner = aws.String(string(f2elemf8iter.MalwareScanner))
					}
					if f2elemf8iter.ScanMode != "" {
						f2elemf8elem.ScanMode = aws.String(string(f2elemf8iter.ScanMode))
					}
					f2elemf8 = append(f2elemf8, f2elemf8elem)
				}
				f2elem.ScanActions = f2elemf8
			}
			if f2iter.ScheduleExpression != nil {
				f2elem.ScheduleExpression = f2iter.ScheduleExpression
			}
			if f2iter.ScheduleExpressionTimezone != nil {
				f2elem.ScheduleExpressionTimezone = f2iter.ScheduleExpressionTimezone
			}
			if f2iter.StartWindowMinutes != nil {
				f2elem.StartWindowMinutes = f2iter.StartWindowMinutes
			}
			if f2iter.TargetBackupVaultName != nil {
				f2elem.TargetBackupVaultName = f2iter.TargetBackupVaultName
			}
			if f2iter.TargetLogicallyAirGappedBackupVaultArn != nil {
				f2elem.TargetLogicallyAirGappedBackupVaultARN = f2iter.TargetLogicallyAirGappedBackupVaultArn
			}
			f2 = append(f2, f2elem)
		}
		ko.Spec.Rules = f2
	} else {
		ko.Spec.Rules = nil
	}
	if resp.BackupPlan.ScanSettings != nil {
		f3 := []*svcapitypes.ScanSetting{}
		for _, f3iter := range resp.BackupPlan.ScanSettings {
			f3elem := &svcapitypes.ScanSetting{}
			if f3iter.MalwareScanner != "" {
				f3elem.MalwareScanner = aws.String(string(f3iter.MalwareScanner))
			}
			if f3iter.ResourceTypes != nil {
				f3elem.ResourceTypes = aws.StringSlice(f3iter.ResourceTypes)
			}
			if f3iter.ScannerRoleArn != nil {
				f3elem.ScannerRoleARN = f3iter.ScannerRoleArn
			}
			f3 = append(f3, f3elem)
		}
		ko.Spec.ScanSettings = f3
	} else {
		ko.Spec.ScanSettings = nil
	}

	rm.setStatusDefaults(ko)
	if err := rm.listTags(ctx, ko); err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetBackupPlanInput, error) {
	res := &svcsdk.GetBackupPlanInput{}

	if r.ko.Status.ID != nil {
		res.BackupPlanId = r.ko.Status.ID
	}
	if r.ko.Status.VersionID != nil {
		res.VersionId = r.ko.Status.VersionID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	// BackupPlanTags is outside the input_wrapper_field_path (BackupPlan).
	// Wire Spec.Tags into the SDK input manually.
	if desired.ko.Spec.Tags != nil {
		input.BackupPlanTags = aws.ToStringMap(desired.ko.Spec.Tags)
	}

	var resp *svcsdk.CreateBackupPlanOutput
	_ = resp
	resp, err = rm.sdkapi.CreateBackupPlan(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateBackupPlan", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AdvancedBackupSettings != nil {
		f0 := []*svcapitypes.AdvancedBackupSetting{}
		for _, f0iter := range resp.AdvancedBackupSettings {
			f0elem := &svcapitypes.AdvancedBackupSetting{}
			if f0iter.BackupOptions != nil {
				f0elem.BackupOptions = aws.StringMap(f0iter.BackupOptions)
			}
			if f0iter.ResourceType != nil {
				f0elem.ResourceType = f0iter.ResourceType
			}
			f0 = append(f0, f0elem)
		}
		ko.Spec.AdvancedBackupSettings = f0
	} else {
		ko.Spec.AdvancedBackupSettings = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.BackupPlanArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.BackupPlanArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.BackupPlanId != nil {
		ko.Status.ID = resp.BackupPlanId
	} else {
		ko.Status.ID = nil
	}
	if resp.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.VersionId != nil {
		ko.Status.VersionID = resp.VersionId
	} else {
		ko.Status.VersionID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateBackupPlanInput, error) {
	res := &svcsdk.CreateBackupPlanInput{}

	fw := &svcsdktypes.BackupPlanInput{}
	if r.ko.Spec.AdvancedBackupSettings != nil {
		f0 := []svcsdktypes.AdvancedBackupSetting{}
		for _, f0iter := range r.ko.Spec.AdvancedBackupSettings {
			f0elem := &svcsdktypes.AdvancedBackupSetting{}
			if f0iter.BackupOptions != nil {
				f0elem.BackupOptions = aws.ToStringMap(f0iter.BackupOptions)
			}
			if f0iter.ResourceType != nil {
				f0elem.ResourceType = f0iter.ResourceType
			}
			f0 = append(f0, *f0elem)
		}
		fw.AdvancedBackupSettings = f0
	}
	if r.ko.Spec.Name != nil {
		fw.BackupPlanName = r.ko.Spec.Name
	}
	if r.ko.Spec.Rules != nil {
		f2 := []svcsdktypes.BackupRuleInput{}
		for _, f2iter := range r.ko.Spec.Rules {
			f2elem := &svcsdktypes.BackupRuleInput{}
			if f2iter.CompletionWindowMinutes != nil {
				f2elem.CompletionWindowMinutes = f2iter.CompletionWindowMinutes
			}
			if f2iter.CopyActions != nil {
				f2elemf1 := []svcsdktypes.CopyAction{}
				for _, f2elemf1iter := range f2iter.CopyActions {
					f2elemf1elem := &svcsdktypes.CopyAction{}
					if f2elemf1iter.DestinationBackupVaultARN != nil {
						f2elemf1elem.DestinationBackupVaultArn = f2elemf1iter.DestinationBackupVaultARN
					}
					if f2elemf1iter.Lifecycle != nil {
						f2elemf1elemf1 := &svcsdktypes.Lifecycle{}
						if f2elemf1iter.Lifecycle.DeleteAfterDays != nil {
							f2elemf1elemf1.DeleteAfterDays = f2elemf1iter.Lifecycle.DeleteAfterDays
						}
						if f2elemf1iter.Lifecycle.DeleteAfterEvent != nil {
							f2elemf1elemf1.DeleteAfterEvent = svcsdktypes.LifecycleDeleteAfterEvent(*f2elemf1iter.Lifecycle.DeleteAfterEvent)
						}
						if f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays != nil {
							f2elemf1elemf1.MoveToColdStorageAfterDays = f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays
						}
						if f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
							f2elemf1elemf1.OptInToArchiveForSupportedResources = f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources
						}
						f2elemf1elem.Lifecycle = f2elemf1elemf1
					}
					f2elemf1 = append(f2elemf1, *f2elemf1elem)
				}
				f2elem.CopyActions = f2elemf1
			}
			if f2iter.EnableContinuousBackup != nil {
				f2elem.EnableContinuousBackup = f2iter.EnableContinuousBackup
			}
			if f2iter.IndexActions != nil {
				f2elemf3 := []svcsdktypes.IndexAction{}
				for _, f2elemf3iter := range f2iter.IndexActions {
					f2elemf3elem := &svcsdktypes.IndexAction{}
					if f2elemf3iter.ResourceTypes != nil {
						f2elemf3elem.ResourceTypes = aws.ToStringSlice(f2elemf3iter.ResourceTypes)
					}
					f2elemf3 = append(f2elemf3, *f2elemf3elem)
				}
				f2elem.IndexActions = f2elemf3
			}
			if f2iter.Lifecycle != nil {
				f2elemf4 := &svcsdktypes.Lifecycle{}
				if f2iter.Lifecycle.DeleteAfterDays != nil {
					f2elemf4.DeleteAfterDays = f2iter.Lifecycle.DeleteAfterDays
				}
				if f2iter.Lifecycle.DeleteAfterEvent != nil {
					f2elemf4.DeleteAfterEvent = svcsdktypes.LifecycleDeleteAfterEvent(*f2iter.Lifecycle.DeleteAfterEvent)
				}
				if f2iter.Lifecycle.MoveToColdStorageAfterDays != nil {
					f2elemf4.MoveToColdStorageAfterDays = f2iter.Lifecycle.MoveToColdStorageAfterDays
				}
				if f2iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
					f2elemf4.OptInToArchiveForSupportedResources = f2iter.Lifecycle.OptInToArchiveForSupportedResources
				}
				f2elem.Lifecycle = f2elemf4
			}
			if f2iter.RecoveryPointTags != nil {
				f2elem.RecoveryPointTags = aws.ToStringMap(f2iter.RecoveryPointTags)
			}
			if f2iter.RuleName != nil {
				f2elem.RuleName = f2iter.RuleName
			}
			if f2iter.ScanActions != nil {
				f2elemf7 := []svcsdktypes.ScanAction{}
				for _, f2elemf7iter := range f2iter.ScanActions {
					f2elemf7elem := &svcsdktypes.ScanAction{}
					if f2elemf7iter.MalwareScanner != nil {
						f2elemf7elem.MalwareScanner = svcsdktypes.MalwareScanner(*f2elemf7iter.MalwareScanner)
					}
					if f2elemf7iter.ScanMode != nil {
						f2elemf7elem.ScanMode = svcsdktypes.ScanMode(*f2elemf7iter.ScanMode)
					}
					f2elemf7 = append(f2elemf7, *f2elemf7elem)
				}
				f2elem.ScanActions = f2elemf7
			}
			if f2iter.ScheduleExpression != nil {
				f2elem.ScheduleExpression = f2iter.ScheduleExpression
			}
			if f2iter.ScheduleExpressionTimezone != nil {
				f2elem.ScheduleExpressionTimezone = f2iter.ScheduleExpressionTimezone
			}
			if f2iter.StartWindowMinutes != nil {
				f2elem.StartWindowMinutes = f2iter.StartWindowMinutes
			}
			if f2iter.TargetBackupVaultName != nil {
				f2elem.TargetBackupVaultName = f2iter.TargetBackupVaultName
			}
			if f2iter.TargetLogicallyAirGappedBackupVaultARN != nil {
				f2elem.TargetLogicallyAirGappedBackupVaultArn = f2iter.TargetLogicallyAirGappedBackupVaultARN
			}
			f2 = append(f2, *f2elem)
		}
		fw.Rules = f2
	}
	if r.ko.Spec.ScanSettings != nil {
		f3 := []svcsdktypes.ScanSetting{}
		for _, f3iter := range r.ko.Spec.ScanSettings {
			f3elem := &svcsdktypes.ScanSetting{}
			if f3iter.MalwareScanner != nil {
				f3elem.MalwareScanner = svcsdktypes.MalwareScanner(*f3iter.MalwareScanner)
			}
			if f3iter.ResourceTypes != nil {
				f3elem.ResourceTypes = aws.ToStringSlice(f3iter.ResourceTypes)
			}
			if f3iter.ScannerRoleARN != nil {
				f3elem.ScannerRoleArn = f3iter.ScannerRoleARN
			}
			f3 = append(f3, *f3elem)
		}
		fw.ScanSettings = f3
	}
	res.BackupPlan = fw

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if err := rm.syncTags(ctx, desired, latest, delta); err != nil {
		return nil, err
	}
	// If only tags changed, no need to call UpdateBackupPlan.
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	// UpdateBackupPlan requires BackupPlanId which is outside the
	// input_wrapper_field_path (BackupPlan). The code generator only
	// populates wrapper fields, so we set the identifier manually.
	if desired.ko.Status.ID != nil {
		input.BackupPlanId = desired.ko.Status.ID
	}

	var resp *svcsdk.UpdateBackupPlanOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateBackupPlan(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateBackupPlan", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AdvancedBackupSettings != nil {
		f0 := []*svcapitypes.AdvancedBackupSetting{}
		for _, f0iter := range resp.AdvancedBackupSettings {
			f0elem := &svcapitypes.AdvancedBackupSetting{}
			if f0iter.BackupOptions != nil {
				f0elem.BackupOptions = aws.StringMap(f0iter.BackupOptions)
			}
			if f0iter.ResourceType != nil {
				f0elem.ResourceType = f0iter.ResourceType
			}
			f0 = append(f0, f0elem)
		}
		ko.Spec.AdvancedBackupSettings = f0
	} else {
		ko.Spec.AdvancedBackupSettings = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.BackupPlanArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.BackupPlanArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.BackupPlanId != nil {
		ko.Status.ID = resp.BackupPlanId
	} else {
		ko.Status.ID = nil
	}
	if resp.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.ScanSettings != nil {
		f4 := []*svcapitypes.ScanSetting{}
		for _, f4iter := range resp.ScanSettings {
			f4elem := &svcapitypes.ScanSetting{}
			if f4iter.MalwareScanner != "" {
				f4elem.MalwareScanner = aws.String(string(f4iter.MalwareScanner))
			}
			if f4iter.ResourceTypes != nil {
				f4elem.ResourceTypes = aws.StringSlice(f4iter.ResourceTypes)
			}
			if f4iter.ScannerRoleArn != nil {
				f4elem.ScannerRoleARN = f4iter.ScannerRoleArn
			}
			f4 = append(f4, f4elem)
		}
		ko.Spec.ScanSettings = f4
	} else {
		ko.Spec.ScanSettings = nil
	}
	if resp.VersionId != nil {
		ko.Status.VersionID = resp.VersionId
	} else {
		ko.Status.VersionID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateBackupPlanInput, error) {
	res := &svcsdk.UpdateBackupPlanInput{}

	fw := &svcsdktypes.BackupPlanInput{}
	if r.ko.Spec.AdvancedBackupSettings != nil {
		f0 := []svcsdktypes.AdvancedBackupSetting{}
		for _, f0iter := range r.ko.Spec.AdvancedBackupSettings {
			f0elem := &svcsdktypes.AdvancedBackupSetting{}
			if f0iter.BackupOptions != nil {
				f0elem.BackupOptions = aws.ToStringMap(f0iter.BackupOptions)
			}
			if f0iter.ResourceType != nil {
				f0elem.ResourceType = f0iter.ResourceType
			}
			f0 = append(f0, *f0elem)
		}
		fw.AdvancedBackupSettings = f0
	}
	if r.ko.Spec.Name != nil {
		fw.BackupPlanName = r.ko.Spec.Name
	}
	if r.ko.Spec.Rules != nil {
		f2 := []svcsdktypes.BackupRuleInput{}
		for _, f2iter := range r.ko.Spec.Rules {
			f2elem := &svcsdktypes.BackupRuleInput{}
			if f2iter.CompletionWindowMinutes != nil {
				f2elem.CompletionWindowMinutes = f2iter.CompletionWindowMinutes
			}
			if f2iter.CopyActions != nil {
				f2elemf1 := []svcsdktypes.CopyAction{}
				for _, f2elemf1iter := range f2iter.CopyActions {
					f2elemf1elem := &svcsdktypes.CopyAction{}
					if f2elemf1iter.DestinationBackupVaultARN != nil {
						f2elemf1elem.DestinationBackupVaultArn = f2elemf1iter.DestinationBackupVaultARN
					}
					if f2elemf1iter.Lifecycle != nil {
						f2elemf1elemf1 := &svcsdktypes.Lifecycle{}
						if f2elemf1iter.Lifecycle.DeleteAfterDays != nil {
							f2elemf1elemf1.DeleteAfterDays = f2elemf1iter.Lifecycle.DeleteAfterDays
						}
						if f2elemf1iter.Lifecycle.DeleteAfterEvent != nil {
							f2elemf1elemf1.DeleteAfterEvent = svcsdktypes.LifecycleDeleteAfterEvent(*f2elemf1iter.Lifecycle.DeleteAfterEvent)
						}
						if f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays != nil {
							f2elemf1elemf1.MoveToColdStorageAfterDays = f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays
						}
						if f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
							f2elemf1elemf1.OptInToArchiveForSupportedResources = f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources
						}
						f2elemf1elem.Lifecycle = f2elemf1elemf1
					}
					f2elemf1 = append(f2elemf1, *f2elemf1elem)
				}
				f2elem.CopyActions = f2elemf1
			}
			if f2iter.EnableContinuousBackup != nil {
				f2elem.EnableContinuousBackup = f2iter.EnableContinuousBackup
			}
			if f2iter.IndexActions != nil {
				f2elemf3 := []svcsdktypes.IndexAction{}
				for _, f2elemf3iter := range f2iter.IndexActions {
					f2elemf3elem := &svcsdktypes.IndexAction{}
					if f2elemf3iter.ResourceTypes != nil {
						f2elemf3elem.ResourceTypes = aws.ToStringSlice(f2elemf3iter.ResourceTypes)
					}
					f2elemf3 = append(f2elemf3, *f2elemf3elem)
				}
				f2elem.IndexActions = f2elemf3
			}
			if f2iter.Lifecycle != nil {
				f2elemf4 := &svcsdktypes.Lifecycle{}
				if f2iter.Lifecycle.DeleteAfterDays != nil {
					f2elemf4.DeleteAfterDays = f2iter.Lifecycle.DeleteAfterDays
				}
				if f2iter.Lifecycle.DeleteAfterEvent != nil {
					f2elemf4.DeleteAfterEvent = svcsdktypes.LifecycleDeleteAfterEvent(*f2iter.Lifecycle.DeleteAfterEvent)
				}
				if f2iter.Lifecycle.MoveToColdStorageAfterDays != nil {
					f2elemf4.MoveToColdStorageAfterDays = f2iter.Lifecycle.MoveToColdStorageAfterDays
				}
				if f2iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
					f2elemf4.OptInToArchiveForSupportedResources = f2iter.Lifecycle.OptInToArchiveForSupportedResources
				}
				f2elem.Lifecycle = f2elemf4
			}
			if f2iter.RecoveryPointTags != nil {
				f2elem.RecoveryPointTags = aws.ToStringMap(f2iter.RecoveryPointTags)
			}
			if f2iter.RuleName != nil {
				f2elem.RuleName = f2iter.RuleName
			}
			if f2iter.ScanActions != nil {
				f2elemf7 := []svcsdktypes.ScanAction{}
				for _, f2elemf7iter := range f2iter.ScanActions {
					f2elemf7elem := &svcsdktypes.ScanAction{}
					if f2elemf7iter.MalwareScanner != nil {
						f2elemf7elem.MalwareScanner = svcsdktypes.MalwareScanner(*f2elemf7iter.MalwareScanner)
					}
					if f2elemf7iter.ScanMode != nil {
						f2elemf7elem.ScanMode = svcsdktypes.ScanMode(*f2elemf7iter.ScanMode)
					}
					f2elemf7 = append(f2elemf7, *f2elemf7elem)
				}
				f2elem.ScanActions = f2elemf7
			}
			if f2iter.ScheduleExpression != nil {
				f2elem.ScheduleExpression = f2iter.ScheduleExpression
			}
			if f2iter.ScheduleExpressionTimezone != nil {
				f2elem.ScheduleExpressionTimezone = f2iter.ScheduleExpressionTimezone
			}
			if f2iter.StartWindowMinutes != nil {
				f2elem.StartWindowMinutes = f2iter.StartWindowMinutes
			}
			if f2iter.TargetBackupVaultName != nil {
				f2elem.TargetBackupVaultName = f2iter.TargetBackupVaultName
			}
			if f2iter.TargetLogicallyAirGappedBackupVaultARN != nil {
				f2elem.TargetLogicallyAirGappedBackupVaultArn = f2iter.TargetLogicallyAirGappedBackupVaultARN
			}
			f2 = append(f2, *f2elem)
		}
		fw.Rules = f2
	}
	if r.ko.Spec.ScanSettings != nil {
		f3 := []svcsdktypes.ScanSetting{}
		for _, f3iter := range r.ko.Spec.ScanSettings {
			f3elem := &svcsdktypes.ScanSetting{}
			if f3iter.MalwareScanner != nil {
				f3elem.MalwareScanner = svcsdktypes.MalwareScanner(*f3iter.MalwareScanner)
			}
			if f3iter.ResourceTypes != nil {
				f3elem.ResourceTypes = aws.ToStringSlice(f3iter.ResourceTypes)
			}
			if f3iter.ScannerRoleARN != nil {
				f3elem.ScannerRoleArn = f3iter.ScannerRoleARN
			}
			f3 = append(f3, *f3elem)
		}
		fw.ScanSettings = f3
	}
	res.BackupPlan = fw

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteBackupPlanOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteBackupPlan(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteBackupPlan", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteBackupPlanInput, error) {
	res := &svcsdk.DeleteBackupPlanInput{}

	if r.ko.Status.ID != nil {
		res.BackupPlanId = r.ko.Status.ID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.BackupPlan,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterValueException",
		"MissingParameterValueException":
		return true
	default:
		return false
	}
}
