// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_selection

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.BackupPlanID, b.ko.Spec.BackupPlanID) {
		delta.Add("Spec.BackupPlanID", a.ko.Spec.BackupPlanID, b.ko.Spec.BackupPlanID)
	} else if a.ko.Spec.BackupPlanID != nil && b.ko.Spec.BackupPlanID != nil {
		if *a.ko.Spec.BackupPlanID != *b.ko.Spec.BackupPlanID {
			delta.Add("Spec.BackupPlanID", a.ko.Spec.BackupPlanID, b.ko.Spec.BackupPlanID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BackupPlanRef, b.ko.Spec.BackupPlanRef) {
		delta.Add("Spec.BackupPlanRef", a.ko.Spec.BackupPlanRef, b.ko.Spec.BackupPlanRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Conditions, b.ko.Spec.Conditions) {
		delta.Add("Spec.Conditions", a.ko.Spec.Conditions, b.ko.Spec.Conditions)
	} else if a.ko.Spec.Conditions != nil && b.ko.Spec.Conditions != nil {
		if len(a.ko.Spec.Conditions.StringEquals) != len(b.ko.Spec.Conditions.StringEquals) {
			delta.Add("Spec.Conditions.StringEquals", a.ko.Spec.Conditions.StringEquals, b.ko.Spec.Conditions.StringEquals)
		} else if len(a.ko.Spec.Conditions.StringEquals) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Conditions.StringEquals, b.ko.Spec.Conditions.StringEquals) {
				delta.Add("Spec.Conditions.StringEquals", a.ko.Spec.Conditions.StringEquals, b.ko.Spec.Conditions.StringEquals)
			}
		}
		if len(a.ko.Spec.Conditions.StringLike) != len(b.ko.Spec.Conditions.StringLike) {
			delta.Add("Spec.Conditions.StringLike", a.ko.Spec.Conditions.StringLike, b.ko.Spec.Conditions.StringLike)
		} else if len(a.ko.Spec.Conditions.StringLike) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Conditions.StringLike, b.ko.Spec.Conditions.StringLike) {
				delta.Add("Spec.Conditions.StringLike", a.ko.Spec.Conditions.StringLike, b.ko.Spec.Conditions.StringLike)
			}
		}
		if len(a.ko.Spec.Conditions.StringNotEquals) != len(b.ko.Spec.Conditions.StringNotEquals) {
			delta.Add("Spec.Conditions.StringNotEquals", a.ko.Spec.Conditions.StringNotEquals, b.ko.Spec.Conditions.StringNotEquals)
		} else if len(a.ko.Spec.Conditions.StringNotEquals) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Conditions.StringNotEquals, b.ko.Spec.Conditions.StringNotEquals) {
				delta.Add("Spec.Conditions.StringNotEquals", a.ko.Spec.Conditions.StringNotEquals, b.ko.Spec.Conditions.StringNotEquals)
			}
		}
		if len(a.ko.Spec.Conditions.StringNotLike) != len(b.ko.Spec.Conditions.StringNotLike) {
			delta.Add("Spec.Conditions.StringNotLike", a.ko.Spec.Conditions.StringNotLike, b.ko.Spec.Conditions.StringNotLike)
		} else if len(a.ko.Spec.Conditions.StringNotLike) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Conditions.StringNotLike, b.ko.Spec.Conditions.StringNotLike) {
				delta.Add("Spec.Conditions.StringNotLike", a.ko.Spec.Conditions.StringNotLike, b.ko.Spec.Conditions.StringNotLike)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.IAMRoleARN, b.ko.Spec.IAMRoleARN) {
		delta.Add("Spec.IAMRoleARN", a.ko.Spec.IAMRoleARN, b.ko.Spec.IAMRoleARN)
	} else if a.ko.Spec.IAMRoleARN != nil && b.ko.Spec.IAMRoleARN != nil {
		if *a.ko.Spec.IAMRoleARN != *b.ko.Spec.IAMRoleARN {
			delta.Add("Spec.IAMRoleARN", a.ko.Spec.IAMRoleARN, b.ko.Spec.IAMRoleARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.IAMRoleRef, b.ko.Spec.IAMRoleRef) {
		delta.Add("Spec.IAMRoleRef", a.ko.Spec.IAMRoleRef, b.ko.Spec.IAMRoleRef)
	}
	if len(a.ko.Spec.ListOfTags) != len(b.ko.Spec.ListOfTags) {
		delta.Add("Spec.ListOfTags", a.ko.Spec.ListOfTags, b.ko.Spec.ListOfTags)
	} else if len(a.ko.Spec.ListOfTags) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ListOfTags, b.ko.Spec.ListOfTags) {
			delta.Add("Spec.ListOfTags", a.ko.Spec.ListOfTags, b.ko.Spec.ListOfTags)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.NotResources) != len(b.ko.Spec.NotResources) {
		delta.Add("Spec.NotResources", a.ko.Spec.NotResources, b.ko.Spec.NotResources)
	} else if len(a.ko.Spec.NotResources) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.NotResources, b.ko.Spec.NotResources) {
			delta.Add("Spec.NotResources", a.ko.Spec.NotResources, b.ko.Spec.NotResources)
		}
	}
	if len(a.ko.Spec.Resources) != len(b.ko.Spec.Resources) {
		delta.Add("Spec.Resources", a.ko.Spec.Resources, b.ko.Spec.Resources)
	} else if len(a.ko.Spec.Resources) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.Resources, b.ko.Spec.Resources) {
			delta.Add("Spec.Resources", a.ko.Spec.Resources, b.ko.Spec.Resources)
		}
	}

	return delta
}
