// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_selection

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/backup"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/backup/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/backup-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.BackupSelection{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetBackupSelectionOutput
	resp, err = rm.sdkapi.GetBackupSelection(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetBackupSelection", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.BackupSelection.Conditions != nil {
		f0 := &svcapitypes.Conditions{}
		if resp.BackupSelection.Conditions.StringEquals != nil {
			f0f0 := []*svcapitypes.ConditionParameter{}
			for _, f0f0iter := range resp.BackupSelection.Conditions.StringEquals {
				f0f0elem := &svcapitypes.ConditionParameter{}
				if f0f0iter.ConditionKey != nil {
					f0f0elem.ConditionKey = f0f0iter.ConditionKey
				}
				if f0f0iter.ConditionValue != nil {
					f0f0elem.ConditionValue = f0f0iter.ConditionValue
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.StringEquals = f0f0
		}
		if resp.BackupSelection.Conditions.StringLike != nil {
			f0f1 := []*svcapitypes.ConditionParameter{}
			for _, f0f1iter := range resp.BackupSelection.Conditions.StringLike {
				f0f1elem := &svcapitypes.ConditionParameter{}
				if f0f1iter.ConditionKey != nil {
					f0f1elem.ConditionKey = f0f1iter.ConditionKey
				}
				if f0f1iter.ConditionValue != nil {
					f0f1elem.ConditionValue = f0f1iter.ConditionValue
				}
				f0f1 = append(f0f1, f0f1elem)
			}
			f0.StringLike = f0f1
		}
		if resp.BackupSelection.Conditions.StringNotEquals != nil {
			f0f2 := []*svcapitypes.ConditionParameter{}
			for _, f0f2iter := range resp.BackupSelection.Conditions.StringNotEquals {
				f0f2elem := &svcapitypes.ConditionParameter{}
				if f0f2iter.ConditionKey != nil {
					f0f2elem.ConditionKey = f0f2iter.ConditionKey
				}
				if f0f2iter.ConditionValue != nil {
					f0f2elem.ConditionValue = f0f2iter.ConditionValue
				}
				f0f2 = append(f0f2, f0f2elem)
			}
			f0.StringNotEquals = f0f2
		}
		if resp.BackupSelection.Conditions.StringNotLike != nil {
			f0f3 := []*svcapitypes.ConditionParameter{}
			for _, f0f3iter := range resp.BackupSelection.Conditions.StringNotLike {
				f0f3elem := &svcapitypes.ConditionParameter{}
				if f0f3iter.ConditionKey != nil {
					f0f3elem.ConditionKey = f0f3iter.ConditionKey
				}
				if f0f3iter.ConditionValue != nil {
					f0f3elem.ConditionValue = f0f3iter.ConditionValue
				}
				f0f3 = append(f0f3, f0f3elem)
			}
			f0.StringNotLike = f0f3
		}
		ko.Spec.Conditions = f0
	} else {
		ko.Spec.Conditions = nil
	}
	if resp.BackupSelection.IamRoleArn != nil {
		ko.Spec.IAMRoleARN = resp.BackupSelection.IamRoleArn
	} else {
		ko.Spec.IAMRoleARN = nil
	}
	if resp.BackupSelection.ListOfTags != nil {
		f2 := []*svcapitypes.Condition{}
		for _, f2iter := range resp.BackupSelection.ListOfTags {
			f2elem := &svcapitypes.Condition{}
			if f2iter.ConditionKey != nil {
				f2elem.ConditionKey = f2iter.ConditionKey
			}
			if f2iter.ConditionType != "" {
				f2elem.ConditionType = aws.String(string(f2iter.ConditionType))
			}
			if f2iter.ConditionValue != nil {
				f2elem.ConditionValue = f2iter.ConditionValue
			}
			f2 = append(f2, f2elem)
		}
		ko.Spec.ListOfTags = f2
	} else {
		ko.Spec.ListOfTags = nil
	}
	if resp.BackupSelection.NotResources != nil {
		ko.Spec.NotResources = aws.StringSlice(resp.BackupSelection.NotResources)
	} else {
		ko.Spec.NotResources = nil
	}
	if resp.BackupSelection.Resources != nil {
		ko.Spec.Resources = aws.StringSlice(resp.BackupSelection.Resources)
	} else {
		ko.Spec.Resources = nil
	}
	if resp.BackupSelection.SelectionName != nil {
		ko.Spec.Name = resp.BackupSelection.SelectionName
	} else {
		ko.Spec.Name = nil
	}

	rm.setStatusDefaults(ko)
	// BackupPlanId is outside the output_wrapper_field_path (BackupSelection).
	// The code generator only populates wrapper fields, so we set it manually.
	if resp.BackupPlanId != nil {
		ko.Spec.BackupPlanID = resp.BackupPlanId
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.BackupPlanID == nil || r.ko.Status.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetBackupSelectionInput, error) {
	res := &svcsdk.GetBackupSelectionInput{}

	if r.ko.Status.BackupPlanID != nil {
		res.BackupPlanId = r.ko.Status.BackupPlanID
	}
	if r.ko.Status.ID != nil {
		res.SelectionId = r.ko.Status.ID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	// BackupPlanId is outside the input_wrapper_field_path (BackupSelection).
	// The code generator only populates wrapper fields, so we set it manually.
	if desired.ko.Spec.BackupPlanID != nil {
		input.BackupPlanId = desired.ko.Spec.BackupPlanID
	}

	var resp *svcsdk.CreateBackupSelectionOutput
	_ = resp
	resp, err = rm.sdkapi.CreateBackupSelection(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateBackupSelection", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.BackupPlanId != nil {
		ko.Status.BackupPlanID = resp.BackupPlanId
	} else {
		ko.Status.BackupPlanID = nil
	}
	if resp.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.SelectionId != nil {
		ko.Status.ID = resp.SelectionId
	} else {
		ko.Status.ID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateBackupSelectionInput, error) {
	res := &svcsdk.CreateBackupSelectionInput{}

	fw := &svcsdktypes.BackupSelection{}
	if r.ko.Spec.Conditions != nil {
		f0 := &svcsdktypes.Conditions{}
		if r.ko.Spec.Conditions.StringEquals != nil {
			f0f0 := []svcsdktypes.ConditionParameter{}
			for _, f0f0iter := range r.ko.Spec.Conditions.StringEquals {
				f0f0elem := &svcsdktypes.ConditionParameter{}
				if f0f0iter.ConditionKey != nil {
					f0f0elem.ConditionKey = f0f0iter.ConditionKey
				}
				if f0f0iter.ConditionValue != nil {
					f0f0elem.ConditionValue = f0f0iter.ConditionValue
				}
				f0f0 = append(f0f0, *f0f0elem)
			}
			f0.StringEquals = f0f0
		}
		if r.ko.Spec.Conditions.StringLike != nil {
			f0f1 := []svcsdktypes.ConditionParameter{}
			for _, f0f1iter := range r.ko.Spec.Conditions.StringLike {
				f0f1elem := &svcsdktypes.ConditionParameter{}
				if f0f1iter.ConditionKey != nil {
					f0f1elem.ConditionKey = f0f1iter.ConditionKey
				}
				if f0f1iter.ConditionValue != nil {
					f0f1elem.ConditionValue = f0f1iter.ConditionValue
				}
				f0f1 = append(f0f1, *f0f1elem)
			}
			f0.StringLike = f0f1
		}
		if r.ko.Spec.Conditions.StringNotEquals != nil {
			f0f2 := []svcsdktypes.ConditionParameter{}
			for _, f0f2iter := range r.ko.Spec.Conditions.StringNotEquals {
				f0f2elem := &svcsdktypes.ConditionParameter{}
				if f0f2iter.ConditionKey != nil {
					f0f2elem.ConditionKey = f0f2iter.ConditionKey
				}
				if f0f2iter.ConditionValue != nil {
					f0f2elem.ConditionValue = f0f2iter.ConditionValue
				}
				f0f2 = append(f0f2, *f0f2elem)
			}
			f0.StringNotEquals = f0f2
		}
		if r.ko.Spec.Conditions.StringNotLike != nil {
			f0f3 := []svcsdktypes.ConditionParameter{}
			for _, f0f3iter := range r.ko.Spec.Conditions.StringNotLike {
				f0f3elem := &svcsdktypes.ConditionParameter{}
				if f0f3iter.ConditionKey != nil {
					f0f3elem.ConditionKey = f0f3iter.ConditionKey
				}
				if f0f3iter.ConditionValue != nil {
					f0f3elem.ConditionValue = f0f3iter.ConditionValue
				}
				f0f3 = append(f0f3, *f0f3elem)
			}
			f0.StringNotLike = f0f3
		}
		fw.Conditions = f0
	}
	if r.ko.Spec.IAMRoleARN != nil {
		fw.IamRoleArn = r.ko.Spec.IAMRoleARN
	}
	if r.ko.Spec.ListOfTags != nil {
		f2 := []svcsdktypes.Condition{}
		for _, f2iter := range r.ko.Spec.ListOfTags {
			f2elem := &svcsdktypes.Condition{}
			if f2iter.ConditionKey != nil {
				f2elem.ConditionKey = f2iter.ConditionKey
			}
			if f2iter.ConditionType != nil {
				f2elem.ConditionType = svcsdktypes.ConditionType(*f2iter.ConditionType)
			}
			if f2iter.ConditionValue != nil {
				f2elem.ConditionValue = f2iter.ConditionValue
			}
			f2 = append(f2, *f2elem)
		}
		fw.ListOfTags = f2
	}
	if r.ko.Spec.NotResources != nil {
		fw.NotResources = aws.ToStringSlice(r.ko.Spec.NotResources)
	}
	if r.ko.Spec.Resources != nil {
		fw.Resources = aws.ToStringSlice(r.ko.Spec.Resources)
	}
	if r.ko.Spec.Name != nil {
		fw.SelectionName = r.ko.Spec.Name
	}
	res.BackupSelection = fw

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateBackupSelection(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// BackupPlanId is outside the input_wrapper_field_path (BackupSelection).
	// Set from status where it was stored after creation.
	if r.ko.Status.BackupPlanID != nil {
		input.BackupPlanId = r.ko.Status.BackupPlanID
	}
	// SelectionId was renamed to ID in the CRD. Code-gen doesn't map it
	// back to the delete input automatically.
	if r.ko.Status.ID != nil {
		input.SelectionId = r.ko.Status.ID
	}

	var resp *svcsdk.DeleteBackupSelectionOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteBackupSelection(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteBackupSelection", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteBackupSelectionInput, error) {
	res := &svcsdk.DeleteBackupSelectionInput{}

	if r.ko.Status.BackupPlanID != nil {
		res.BackupPlanId = r.ko.Status.BackupPlanID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.BackupSelection,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterValueException",
		"MissingParameterValueException":
		return true
	default:
		return false
	}
}
