// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackupSelectionSpec defines the desired state of BackupSelection.
type BackupSelectionSpec struct {

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	BackupPlanID  *string                                  `json:"backupPlanID,omitempty"`
	BackupPlanRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"backupPlanRef,omitempty"`
	// The conditions that you define to assign resources to your backup plans using
	// tags. For example, "StringEquals": { "ConditionKey": "aws:ResourceTag/backup",
	// "ConditionValue": "daily" }.
	//
	// Conditions supports StringEquals, StringLike, StringNotEquals, and StringNotLike.
	// Condition operators are case sensitive.
	//
	// If you specify multiple conditions, the resources much match all conditions
	// (AND logic).
	Conditions *Conditions `json:"conditions,omitempty"`
	// The ARN of the IAM role that Backup uses to authenticate when backing up
	// the target resource; for example, arn:aws:iam::123456789012:role/S3Access.
	IAMRoleARN *string                                  `json:"iamRoleARN,omitempty"`
	IAMRoleRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"iamRoleRef,omitempty"`
	// The conditions that you define to assign resources to your backup plans using
	// tags. For example, "StringEquals": { "ConditionKey": "backup", "ConditionValue":
	// "daily"}.
	//
	// ListOfTags supports only StringEquals. Condition operators are case sensitive.
	//
	// If you specify multiple conditions, the resources much match any of the conditions
	// (OR logic).
	ListOfTags []*Condition `json:"listOfTags,omitempty"`
	// The display name of a resource selection document. Must contain 1 to 50 alphanumeric
	// or '-_.' characters.
	//
	// Regex Pattern: `^[a-zA-Z0-9\-\_\.]{1,50}$`
	Name *string `json:"name,omitempty"`
	// The Amazon Resource Names (ARNs) of the resources to exclude from a backup
	// plan. The maximum number of ARNs is 500 without wildcards, or 30 ARNs with
	// wildcards.
	//
	// If you need to exclude many resources from a backup plan, consider a different
	// resource selection strategy, such as assigning only one or a few resource
	// types or refining your resource selection using tags.
	NotResources []*string `json:"notResources,omitempty"`
	// The Amazon Resource Names (ARNs) of the resources to assign to a backup plan.
	// The maximum number of ARNs is 500 without wildcards, or 30 ARNs with wildcards.
	//
	// If you need to assign many resources to a backup plan, consider a different
	// resource selection strategy, such as assigning all resources of a resource
	// type or refining your resource selection using tags.
	//
	// If you specify multiple ARNs, the resources much match any of the ARNs (OR
	// logic).
	//
	// When using wildcards in ARN patterns for backup selections, the asterisk
	// (*) must appear at the end of the ARN string (prefix pattern). For example,
	// arn:aws:s3:::my-bucket-* is valid, but arn:aws:s3:::*-logs is not supported.
	Resources []*string `json:"resources,omitempty"`
}

// BackupSelectionStatus defines the observed state of BackupSelection
type BackupSelectionStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The ID of the backup plan.
	// +kubebuilder:validation:Optional
	BackupPlanID *string `json:"backupPlanID,omitempty"`
	// The date and time a backup selection is created, in Unix format and Coordinated
	// Universal Time (UTC). The value of CreationDate is accurate to milliseconds.
	// For example, the value 1516925490.087 represents Friday, January 26, 2018
	// 12:11:30.087 AM.
	// +kubebuilder:validation:Optional
	CreationDate *metav1.Time `json:"creationDate,omitempty"`
	// Uniquely identifies the body of a request to assign a set of resources to
	// a backup plan.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
}

// BackupSelection is the Schema for the BackupSelections API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type BackupSelection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BackupSelectionSpec   `json:"spec,omitempty"`
	Status            BackupSelectionStatus `json:"status,omitempty"`
}

// BackupSelectionList contains a list of BackupSelection
// +kubebuilder:object:root=true
type BackupSelectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupSelection `json:"items"`
}

func init() {
	SchemeBuilder.Register(&BackupSelection{}, &BackupSelectionList{})
}
