// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackupPlanSpec defines the desired state of BackupPlan.
type BackupPlanSpec struct {

	// Specifies a list of BackupOptions for each resource type. These settings
	// are only available for Windows Volume Shadow Copy Service (VSS) backup jobs.
	AdvancedBackupSettings []*AdvancedBackupSetting `json:"advancedBackupSettings,omitempty"`
	// The display name of a backup plan. Must contain 1 to 50 alphanumeric or '-_.'
	// characters.
	Name *string `json:"name,omitempty"`
	// An array of BackupRule objects, each of which specifies a scheduled task
	// that is used to back up a selection of resources.
	Rules []*RuleInput `json:"rules,omitempty"`
	// Contains your scanning configuration for the backup rule and includes the
	// malware scanner, and scan mode of either full or incremental.
	ScanSettings []*ScanSetting     `json:"scanSettings,omitempty"`
	Tags         map[string]*string `json:"tags,omitempty"`
}

// BackupPlanStatus defines the observed state of BackupPlan
type BackupPlanStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time that a backup plan is created, in Unix format and Coordinated
	// Universal Time (UTC). The value of CreationDate is accurate to milliseconds.
	// For example, the value 1516925490.087 represents Friday, January 26, 2018
	// 12:11:30.087 AM.
	// +kubebuilder:validation:Optional
	CreationDate *metav1.Time `json:"creationDate,omitempty"`
	// The ID of the backup plan.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The last time this backup plan was run. A date and time, in Unix format and
	// Coordinated Universal Time (UTC). The value of LastExecutionDate is accurate
	// to milliseconds. For example, the value 1516925490.087 represents Friday,
	// January 26, 2018 12:11:30.087 AM.
	// +kubebuilder:validation:Optional
	LastExecutionDate *metav1.Time `json:"lastExecutionDate,omitempty"`
	// Unique, randomly generated, Unicode, UTF-8 encoded strings that are at most
	// 1,024 bytes long. They cannot be edited.
	// +kubebuilder:validation:Optional
	VersionID *string `json:"versionID,omitempty"`
}

// BackupPlan is the Schema for the BackupPlans API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type BackupPlan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BackupPlanSpec   `json:"spec,omitempty"`
	Status            BackupPlanStatus `json:"status,omitempty"`
}

// BackupPlanList contains a list of BackupPlan
// +kubebuilder:object:root=true
type BackupPlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupPlan `json:"items"`
}

func init() {
	SchemeBuilder.Register(&BackupPlan{}, &BackupPlanList{})
}
