// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AggregationPeriod string

const (
	AggregationPeriod_FOURTEEN_DAYS AggregationPeriod = "FOURTEEN_DAYS"
	AggregationPeriod_ONE_DAY       AggregationPeriod = "ONE_DAY"
	AggregationPeriod_SEVEN_DAYS    AggregationPeriod = "SEVEN_DAYS"
)

type BackupJobStatus string

const (
	BackupJobStatus_ABORTED       BackupJobStatus = "ABORTED"
	BackupJobStatus_ABORTING      BackupJobStatus = "ABORTING"
	BackupJobStatus_AGGREGATE_ALL BackupJobStatus = "AGGREGATE_ALL"
	BackupJobStatus_ANY           BackupJobStatus = "ANY"
	BackupJobStatus_COMPLETED     BackupJobStatus = "COMPLETED"
	BackupJobStatus_CREATED       BackupJobStatus = "CREATED"
	BackupJobStatus_EXPIRED       BackupJobStatus = "EXPIRED"
	BackupJobStatus_FAILED        BackupJobStatus = "FAILED"
	BackupJobStatus_PARTIAL       BackupJobStatus = "PARTIAL"
	BackupJobStatus_PENDING       BackupJobStatus = "PENDING"
	BackupJobStatus_RUNNING       BackupJobStatus = "RUNNING"
)

type ConditionType string

const (
	ConditionType_STRINGEQUALS ConditionType = "STRINGEQUALS"
)

type CopyJobState string

const (
	CopyJobState_COMPLETED CopyJobState = "COMPLETED"
	CopyJobState_CREATED   CopyJobState = "CREATED"
	CopyJobState_FAILED    CopyJobState = "FAILED"
	CopyJobState_PARTIAL   CopyJobState = "PARTIAL"
	CopyJobState_RUNNING   CopyJobState = "RUNNING"
)

type CopyJobStatus string

const (
	CopyJobStatus_ABORTED       CopyJobStatus = "ABORTED"
	CopyJobStatus_ABORTING      CopyJobStatus = "ABORTING"
	CopyJobStatus_AGGREGATE_ALL CopyJobStatus = "AGGREGATE_ALL"
	CopyJobStatus_ANY           CopyJobStatus = "ANY"
	CopyJobStatus_COMPLETED     CopyJobStatus = "COMPLETED"
	CopyJobStatus_COMPLETING    CopyJobStatus = "COMPLETING"
	CopyJobStatus_CREATED       CopyJobStatus = "CREATED"
	CopyJobStatus_FAILED        CopyJobStatus = "FAILED"
	CopyJobStatus_FAILING       CopyJobStatus = "FAILING"
	CopyJobStatus_PARTIAL       CopyJobStatus = "PARTIAL"
	CopyJobStatus_RUNNING       CopyJobStatus = "RUNNING"
)

type EncryptionKeyType string

const (
	EncryptionKeyType_AWS_OWNED_KMS_KEY        EncryptionKeyType = "AWS_OWNED_KMS_KEY"
	EncryptionKeyType_CUSTOMER_MANAGED_KMS_KEY EncryptionKeyType = "CUSTOMER_MANAGED_KMS_KEY"
)

type Index string

const (
	Index_DISABLED Index = "DISABLED"
	Index_ENABLED  Index = "ENABLED"
)

type IndexStatus string

const (
	IndexStatus_ACTIVE   IndexStatus = "ACTIVE"
	IndexStatus_DELETING IndexStatus = "DELETING"
	IndexStatus_FAILED   IndexStatus = "FAILED"
	IndexStatus_PENDING  IndexStatus = "PENDING"
)

type JobState string

const (
	JobState_ABORTED   JobState = "ABORTED"
	JobState_ABORTING  JobState = "ABORTING"
	JobState_COMPLETED JobState = "COMPLETED"
	JobState_CREATED   JobState = "CREATED"
	JobState_EXPIRED   JobState = "EXPIRED"
	JobState_FAILED    JobState = "FAILED"
	JobState_PARTIAL   JobState = "PARTIAL"
	JobState_PENDING   JobState = "PENDING"
	JobState_RUNNING   JobState = "RUNNING"
)

type LegalHoldStatus string

const (
	LegalHoldStatus_ACTIVE    LegalHoldStatus = "ACTIVE"
	LegalHoldStatus_CANCELED  LegalHoldStatus = "CANCELED"
	LegalHoldStatus_CANCELING LegalHoldStatus = "CANCELING"
	LegalHoldStatus_CREATING  LegalHoldStatus = "CREATING"
)

type LifecycleDeleteAfterEvent string

const (
	LifecycleDeleteAfterEvent_DELETE_AFTER_COPY LifecycleDeleteAfterEvent = "DELETE_AFTER_COPY"
)

type MalwareScanner string

const (
	MalwareScanner_GUARDDUTY MalwareScanner = "GUARDDUTY"
)

type MpaRevokeSessionStatus string

const (
	MpaRevokeSessionStatus_FAILED  MpaRevokeSessionStatus = "FAILED"
	MpaRevokeSessionStatus_PENDING MpaRevokeSessionStatus = "PENDING"
)

type MpaSessionStatus string

const (
	MpaSessionStatus_APPROVED MpaSessionStatus = "APPROVED"
	MpaSessionStatus_FAILED   MpaSessionStatus = "FAILED"
	MpaSessionStatus_PENDING  MpaSessionStatus = "PENDING"
)

type RecoveryPointStatus string

const (
	RecoveryPointStatus_AVAILABLE RecoveryPointStatus = "AVAILABLE"
	RecoveryPointStatus_COMPLETED RecoveryPointStatus = "COMPLETED"
	RecoveryPointStatus_CREATING  RecoveryPointStatus = "CREATING"
	RecoveryPointStatus_DELETING  RecoveryPointStatus = "DELETING"
	RecoveryPointStatus_EXPIRED   RecoveryPointStatus = "EXPIRED"
	RecoveryPointStatus_PARTIAL   RecoveryPointStatus = "PARTIAL"
	RecoveryPointStatus_STOPPED   RecoveryPointStatus = "STOPPED"
)

type RestoreDeletionStatus string

const (
	RestoreDeletionStatus_DELETING   RestoreDeletionStatus = "DELETING"
	RestoreDeletionStatus_FAILED     RestoreDeletionStatus = "FAILED"
	RestoreDeletionStatus_SUCCESSFUL RestoreDeletionStatus = "SUCCESSFUL"
)

type RestoreJobState string

const (
	RestoreJobState_ABORTED       RestoreJobState = "ABORTED"
	RestoreJobState_AGGREGATE_ALL RestoreJobState = "AGGREGATE_ALL"
	RestoreJobState_ANY           RestoreJobState = "ANY"
	RestoreJobState_COMPLETED     RestoreJobState = "COMPLETED"
	RestoreJobState_CREATED       RestoreJobState = "CREATED"
	RestoreJobState_FAILED        RestoreJobState = "FAILED"
	RestoreJobState_PENDING       RestoreJobState = "PENDING"
	RestoreJobState_RUNNING       RestoreJobState = "RUNNING"
)

type RestoreJobStatus string

const (
	RestoreJobStatus_ABORTED   RestoreJobStatus = "ABORTED"
	RestoreJobStatus_COMPLETED RestoreJobStatus = "COMPLETED"
	RestoreJobStatus_FAILED    RestoreJobStatus = "FAILED"
	RestoreJobStatus_PENDING   RestoreJobStatus = "PENDING"
	RestoreJobStatus_RUNNING   RestoreJobStatus = "RUNNING"
)

type RestoreTestingRecoveryPointSelectionAlgorithm string

const (
	RestoreTestingRecoveryPointSelectionAlgorithm_LATEST_WITHIN_WINDOW RestoreTestingRecoveryPointSelectionAlgorithm = "LATEST_WITHIN_WINDOW"
	RestoreTestingRecoveryPointSelectionAlgorithm_RANDOM_WITHIN_WINDOW RestoreTestingRecoveryPointSelectionAlgorithm = "RANDOM_WITHIN_WINDOW"
)

type RestoreTestingRecoveryPointType string

const (
	RestoreTestingRecoveryPointType_CONTINUOUS RestoreTestingRecoveryPointType = "CONTINUOUS"
	RestoreTestingRecoveryPointType_SNAPSHOT   RestoreTestingRecoveryPointType = "SNAPSHOT"
)

type RestoreValidationStatus string

const (
	RestoreValidationStatus_FAILED     RestoreValidationStatus = "FAILED"
	RestoreValidationStatus_SUCCESSFUL RestoreValidationStatus = "SUCCESSFUL"
	RestoreValidationStatus_TIMED_OUT  RestoreValidationStatus = "TIMED_OUT"
	RestoreValidationStatus_VALIDATING RestoreValidationStatus = "VALIDATING"
)

type RuleExecutionType string

const (
	RuleExecutionType_CONTINUOUS               RuleExecutionType = "CONTINUOUS"
	RuleExecutionType_CONTINUOUS_AND_SNAPSHOTS RuleExecutionType = "CONTINUOUS_AND_SNAPSHOTS"
	RuleExecutionType_SNAPSHOTS                RuleExecutionType = "SNAPSHOTS"
)

type ScanFinding string

const (
	ScanFinding_MALWARE ScanFinding = "MALWARE"
)

type ScanJobState string

const (
	ScanJobState_CANCELED              ScanJobState = "CANCELED"
	ScanJobState_COMPLETED             ScanJobState = "COMPLETED"
	ScanJobState_COMPLETED_WITH_ISSUES ScanJobState = "COMPLETED_WITH_ISSUES"
	ScanJobState_FAILED                ScanJobState = "FAILED"
)

type ScanJobStatus string

const (
	ScanJobStatus_AGGREGATE_ALL         ScanJobStatus = "AGGREGATE_ALL"
	ScanJobStatus_ANY                   ScanJobStatus = "ANY"
	ScanJobStatus_CANCELED              ScanJobStatus = "CANCELED"
	ScanJobStatus_COMPLETED             ScanJobStatus = "COMPLETED"
	ScanJobStatus_COMPLETED_WITH_ISSUES ScanJobStatus = "COMPLETED_WITH_ISSUES"
	ScanJobStatus_CREATED               ScanJobStatus = "CREATED"
	ScanJobStatus_FAILED                ScanJobStatus = "FAILED"
	ScanJobStatus_RUNNING               ScanJobStatus = "RUNNING"
)

type ScanMode string

const (
	ScanMode_FULL_SCAN        ScanMode = "FULL_SCAN"
	ScanMode_INCREMENTAL_SCAN ScanMode = "INCREMENTAL_SCAN"
)

type ScanResourceType string

const (
	ScanResourceType_EBS ScanResourceType = "EBS"
	ScanResourceType_EC2 ScanResourceType = "EC2"
	ScanResourceType_S3  ScanResourceType = "S3"
)

type ScanResultStatus string

const (
	ScanResultStatus_NO_THREATS_FOUND ScanResultStatus = "NO_THREATS_FOUND"
	ScanResultStatus_THREATS_FOUND    ScanResultStatus = "THREATS_FOUND"
)

type ScanState string

const (
	ScanState_CANCELED              ScanState = "CANCELED"
	ScanState_COMPLETED             ScanState = "COMPLETED"
	ScanState_COMPLETED_WITH_ISSUES ScanState = "COMPLETED_WITH_ISSUES"
	ScanState_CREATED               ScanState = "CREATED"
	ScanState_FAILED                ScanState = "FAILED"
	ScanState_RUNNING               ScanState = "RUNNING"
)

type StorageClass string

const (
	StorageClass_COLD    StorageClass = "COLD"
	StorageClass_DELETED StorageClass = "DELETED"
	StorageClass_WARM    StorageClass = "WARM"
)

type VaultEvent string

const (
	VaultEvent_BACKUP_JOB_COMPLETED           VaultEvent = "BACKUP_JOB_COMPLETED"
	VaultEvent_BACKUP_JOB_EXPIRED             VaultEvent = "BACKUP_JOB_EXPIRED"
	VaultEvent_BACKUP_JOB_FAILED              VaultEvent = "BACKUP_JOB_FAILED"
	VaultEvent_BACKUP_JOB_STARTED             VaultEvent = "BACKUP_JOB_STARTED"
	VaultEvent_BACKUP_JOB_SUCCESSFUL          VaultEvent = "BACKUP_JOB_SUCCESSFUL"
	VaultEvent_BACKUP_PLAN_CREATED            VaultEvent = "BACKUP_PLAN_CREATED"
	VaultEvent_BACKUP_PLAN_MODIFIED           VaultEvent = "BACKUP_PLAN_MODIFIED"
	VaultEvent_CONTINUOUS_BACKUP_INTERRUPTED  VaultEvent = "CONTINUOUS_BACKUP_INTERRUPTED"
	VaultEvent_COPY_JOB_FAILED                VaultEvent = "COPY_JOB_FAILED"
	VaultEvent_COPY_JOB_STARTED               VaultEvent = "COPY_JOB_STARTED"
	VaultEvent_COPY_JOB_SUCCESSFUL            VaultEvent = "COPY_JOB_SUCCESSFUL"
	VaultEvent_RECOVERY_POINT_INDEXING_FAILED VaultEvent = "RECOVERY_POINT_INDEXING_FAILED"
	VaultEvent_RECOVERY_POINT_INDEX_COMPLETED VaultEvent = "RECOVERY_POINT_INDEX_COMPLETED"
	VaultEvent_RECOVERY_POINT_INDEX_DELETED   VaultEvent = "RECOVERY_POINT_INDEX_DELETED"
	VaultEvent_RECOVERY_POINT_MODIFIED        VaultEvent = "RECOVERY_POINT_MODIFIED"
	VaultEvent_RESTORE_JOB_COMPLETED          VaultEvent = "RESTORE_JOB_COMPLETED"
	VaultEvent_RESTORE_JOB_FAILED             VaultEvent = "RESTORE_JOB_FAILED"
	VaultEvent_RESTORE_JOB_STARTED            VaultEvent = "RESTORE_JOB_STARTED"
	VaultEvent_RESTORE_JOB_SUCCESSFUL         VaultEvent = "RESTORE_JOB_SUCCESSFUL"
	VaultEvent_S3_BACKUP_OBJECT_FAILED        VaultEvent = "S3_BACKUP_OBJECT_FAILED"
	VaultEvent_S3_RESTORE_OBJECT_FAILED       VaultEvent = "S3_RESTORE_OBJECT_FAILED"
)

type VaultState string

const (
	VaultState_AVAILABLE VaultState = "AVAILABLE"
	VaultState_CREATING  VaultState = "CREATING"
	VaultState_FAILED    VaultState = "FAILED"
)

type VaultType string

const (
	VaultType_BACKUP_VAULT                      VaultType = "BACKUP_VAULT"
	VaultType_LOGICALLY_AIR_GAPPED_BACKUP_VAULT VaultType = "LOGICALLY_AIR_GAPPED_BACKUP_VAULT"
	VaultType_RESTORE_ACCESS_BACKUP_VAULT       VaultType = "RESTORE_ACCESS_BACKUP_VAULT"
)
