//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedBackupSetting) DeepCopyInto(out *AdvancedBackupSetting) {
	*out = *in
	if in.BackupOptions != nil {
		in, out := &in.BackupOptions, &out.BackupOptions
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedBackupSetting.
func (in *AdvancedBackupSetting) DeepCopy() *AdvancedBackupSetting {
	if in == nil {
		return nil
	}
	out := new(AdvancedBackupSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregatedScanResult) DeepCopyInto(out *AggregatedScanResult) {
	*out = *in
	if in.FailedScan != nil {
		in, out := &in.FailedScan, &out.FailedScan
		*out = new(bool)
		**out = **in
	}
	if in.LastComputed != nil {
		in, out := &in.LastComputed, &out.LastComputed
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregatedScanResult.
func (in *AggregatedScanResult) DeepCopy() *AggregatedScanResult {
	if in == nil {
		return nil
	}
	out := new(AggregatedScanResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupJobSummary) DeepCopyInto(out *BackupJobSummary) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupJobSummary.
func (in *BackupJobSummary) DeepCopy() *BackupJobSummary {
	if in == nil {
		return nil
	}
	out := new(BackupJobSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPlan) DeepCopyInto(out *BackupPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPlan.
func (in *BackupPlan) DeepCopy() *BackupPlan {
	if in == nil {
		return nil
	}
	out := new(BackupPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPlanList) DeepCopyInto(out *BackupPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPlanList.
func (in *BackupPlanList) DeepCopy() *BackupPlanList {
	if in == nil {
		return nil
	}
	out := new(BackupPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPlanSpec) DeepCopyInto(out *BackupPlanSpec) {
	*out = *in
	if in.AdvancedBackupSettings != nil {
		in, out := &in.AdvancedBackupSettings, &out.AdvancedBackupSettings
		*out = make([]*AdvancedBackupSetting, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AdvancedBackupSetting)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]*RuleInput, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RuleInput)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ScanSettings != nil {
		in, out := &in.ScanSettings, &out.ScanSettings
		*out = make([]*ScanSetting, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ScanSetting)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPlanSpec.
func (in *BackupPlanSpec) DeepCopy() *BackupPlanSpec {
	if in == nil {
		return nil
	}
	out := new(BackupPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPlanStatus) DeepCopyInto(out *BackupPlanStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastExecutionDate != nil {
		in, out := &in.LastExecutionDate, &out.LastExecutionDate
		*out = (*in).DeepCopy()
	}
	if in.VersionID != nil {
		in, out := &in.VersionID, &out.VersionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPlanStatus.
func (in *BackupPlanStatus) DeepCopy() *BackupPlanStatus {
	if in == nil {
		return nil
	}
	out := new(BackupPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupVault) DeepCopyInto(out *BackupVault) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupVault.
func (in *BackupVault) DeepCopy() *BackupVault {
	if in == nil {
		return nil
	}
	out := new(BackupVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupVault) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupVaultList) DeepCopyInto(out *BackupVaultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupVault, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupVaultList.
func (in *BackupVaultList) DeepCopy() *BackupVaultList {
	if in == nil {
		return nil
	}
	out := new(BackupVaultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupVaultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupVaultSpec) DeepCopyInto(out *BackupVaultSpec) {
	*out = *in
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyRef != nil {
		in, out := &in.EncryptionKeyRef, &out.EncryptionKeyRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupVaultSpec.
func (in *BackupVaultSpec) DeepCopy() *BackupVaultSpec {
	if in == nil {
		return nil
	}
	out := new(BackupVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupVaultStatus) DeepCopyInto(out *BackupVaultStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.EncryptionKeyType != nil {
		in, out := &in.EncryptionKeyType, &out.EncryptionKeyType
		*out = new(string)
		**out = **in
	}
	if in.LockDate != nil {
		in, out := &in.LockDate, &out.LockDate
		*out = (*in).DeepCopy()
	}
	if in.Locked != nil {
		in, out := &in.Locked, &out.Locked
		*out = new(bool)
		**out = **in
	}
	if in.MaxRetentionDays != nil {
		in, out := &in.MaxRetentionDays, &out.MaxRetentionDays
		*out = new(int64)
		**out = **in
	}
	if in.MinRetentionDays != nil {
		in, out := &in.MinRetentionDays, &out.MinRetentionDays
		*out = new(int64)
		**out = **in
	}
	if in.NumberOfRecoveryPoints != nil {
		in, out := &in.NumberOfRecoveryPoints, &out.NumberOfRecoveryPoints
		*out = new(int64)
		**out = **in
	}
	if in.VaultType != nil {
		in, out := &in.VaultType, &out.VaultType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupVaultStatus.
func (in *BackupVaultStatus) DeepCopy() *BackupVaultStatus {
	if in == nil {
		return nil
	}
	out := new(BackupVaultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalculatedLifecycle) DeepCopyInto(out *CalculatedLifecycle) {
	*out = *in
	if in.DeleteAt != nil {
		in, out := &in.DeleteAt, &out.DeleteAt
		*out = (*in).DeepCopy()
	}
	if in.MoveToColdStorageAt != nil {
		in, out := &in.MoveToColdStorageAt, &out.MoveToColdStorageAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalculatedLifecycle.
func (in *CalculatedLifecycle) DeepCopy() *CalculatedLifecycle {
	if in == nil {
		return nil
	}
	out := new(CalculatedLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyAction) DeepCopyInto(out *CopyAction) {
	*out = *in
	if in.DestinationBackupVaultARN != nil {
		in, out := &in.DestinationBackupVaultARN, &out.DestinationBackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.DestinationBackupVaultRef != nil {
		in, out := &in.DestinationBackupVaultRef, &out.DestinationBackupVaultRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(Lifecycle)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyAction.
func (in *CopyAction) DeepCopy() *CopyAction {
	if in == nil {
		return nil
	}
	out := new(CopyAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyJob) DeepCopyInto(out *CopyJob) {
	*out = *in
	if in.BackupSizeInBytes != nil {
		in, out := &in.BackupSizeInBytes, &out.BackupSizeInBytes
		*out = new(int64)
		**out = **in
	}
	if in.CompletionDate != nil {
		in, out := &in.CompletionDate, &out.CompletionDate
		*out = (*in).DeepCopy()
	}
	if in.CompositeMemberIdentifier != nil {
		in, out := &in.CompositeMemberIdentifier, &out.CompositeMemberIdentifier
		*out = new(string)
		**out = **in
	}
	if in.CopyJobID != nil {
		in, out := &in.CopyJobID, &out.CopyJobID
		*out = new(string)
		**out = **in
	}
	if in.CreatedByBackupJobID != nil {
		in, out := &in.CreatedByBackupJobID, &out.CreatedByBackupJobID
		*out = new(string)
		**out = **in
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.DestinationBackupVaultARN != nil {
		in, out := &in.DestinationBackupVaultARN, &out.DestinationBackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.DestinationEncryptionKeyARN != nil {
		in, out := &in.DestinationEncryptionKeyARN, &out.DestinationEncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.DestinationRecoveryPointARN != nil {
		in, out := &in.DestinationRecoveryPointARN, &out.DestinationRecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.DestinationRecoveryPointLifecycle != nil {
		in, out := &in.DestinationRecoveryPointLifecycle, &out.DestinationRecoveryPointLifecycle
		*out = new(Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	if in.DestinationVaultLockState != nil {
		in, out := &in.DestinationVaultLockState, &out.DestinationVaultLockState
		*out = new(string)
		**out = **in
	}
	if in.DestinationVaultType != nil {
		in, out := &in.DestinationVaultType, &out.DestinationVaultType
		*out = new(string)
		**out = **in
	}
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
	if in.IsParent != nil {
		in, out := &in.IsParent, &out.IsParent
		*out = new(bool)
		**out = **in
	}
	if in.MessageCategory != nil {
		in, out := &in.MessageCategory, &out.MessageCategory
		*out = new(string)
		**out = **in
	}
	if in.NumberOfChildJobs != nil {
		in, out := &in.NumberOfChildJobs, &out.NumberOfChildJobs
		*out = new(int64)
		**out = **in
	}
	if in.ParentJobID != nil {
		in, out := &in.ParentJobID, &out.ParentJobID
		*out = new(string)
		**out = **in
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.SourceBackupVaultARN != nil {
		in, out := &in.SourceBackupVaultARN, &out.SourceBackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.SourceRecoveryPointARN != nil {
		in, out := &in.SourceRecoveryPointARN, &out.SourceRecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyJob.
func (in *CopyJob) DeepCopy() *CopyJob {
	if in == nil {
		return nil
	}
	out := new(CopyJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyJobSummary) DeepCopyInto(out *CopyJobSummary) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyJobSummary.
func (in *CopyJobSummary) DeepCopy() *CopyJobSummary {
	if in == nil {
		return nil
	}
	out := new(CopyJobSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DateRange) DeepCopyInto(out *DateRange) {
	*out = *in
	if in.FromDate != nil {
		in, out := &in.FromDate, &out.FromDate
		*out = (*in).DeepCopy()
	}
	if in.ToDate != nil {
		in, out := &in.ToDate, &out.ToDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DateRange.
func (in *DateRange) DeepCopy() *DateRange {
	if in == nil {
		return nil
	}
	out := new(DateRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Framework) DeepCopyInto(out *Framework) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.DeploymentStatus != nil {
		in, out := &in.DeploymentStatus, &out.DeploymentStatus
		*out = new(string)
		**out = **in
	}
	if in.FrameworkARN != nil {
		in, out := &in.FrameworkARN, &out.FrameworkARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Framework.
func (in *Framework) DeepCopy() *Framework {
	if in == nil {
		return nil
	}
	out := new(Framework)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexAction) DeepCopyInto(out *IndexAction) {
	*out = *in
	if in.ResourceTypes != nil {
		in, out := &in.ResourceTypes, &out.ResourceTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexAction.
func (in *IndexAction) DeepCopy() *IndexAction {
	if in == nil {
		return nil
	}
	out := new(IndexAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexedRecoveryPoint) DeepCopyInto(out *IndexedRecoveryPoint) {
	*out = *in
	if in.BackupCreationDate != nil {
		in, out := &in.BackupCreationDate, &out.BackupCreationDate
		*out = (*in).DeepCopy()
	}
	if in.BackupVaultARN != nil {
		in, out := &in.BackupVaultARN, &out.BackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
	if in.IndexCreationDate != nil {
		in, out := &in.IndexCreationDate, &out.IndexCreationDate
		*out = (*in).DeepCopy()
	}
	if in.IndexStatusMessage != nil {
		in, out := &in.IndexStatusMessage, &out.IndexStatusMessage
		*out = new(string)
		**out = **in
	}
	if in.RecoveryPointARN != nil {
		in, out := &in.RecoveryPointARN, &out.RecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.SourceResourceARN != nil {
		in, out := &in.SourceResourceARN, &out.SourceResourceARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexedRecoveryPoint.
func (in *IndexedRecoveryPoint) DeepCopy() *IndexedRecoveryPoint {
	if in == nil {
		return nil
	}
	out := new(IndexedRecoveryPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Job) DeepCopyInto(out *Job) {
	*out = *in
	if in.BackupJobID != nil {
		in, out := &in.BackupJobID, &out.BackupJobID
		*out = new(string)
		**out = **in
	}
	if in.BackupOptions != nil {
		in, out := &in.BackupOptions, &out.BackupOptions
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.BackupSizeInBytes != nil {
		in, out := &in.BackupSizeInBytes, &out.BackupSizeInBytes
		*out = new(int64)
		**out = **in
	}
	if in.BackupType != nil {
		in, out := &in.BackupType, &out.BackupType
		*out = new(string)
		**out = **in
	}
	if in.BackupVaultARN != nil {
		in, out := &in.BackupVaultARN, &out.BackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.BackupVaultName != nil {
		in, out := &in.BackupVaultName, &out.BackupVaultName
		*out = new(string)
		**out = **in
	}
	if in.BytesTransferred != nil {
		in, out := &in.BytesTransferred, &out.BytesTransferred
		*out = new(int64)
		**out = **in
	}
	if in.CompletionDate != nil {
		in, out := &in.CompletionDate, &out.CompletionDate
		*out = (*in).DeepCopy()
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.ExpectedCompletionDate != nil {
		in, out := &in.ExpectedCompletionDate, &out.ExpectedCompletionDate
		*out = (*in).DeepCopy()
	}
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
	if in.InitiationDate != nil {
		in, out := &in.InitiationDate, &out.InitiationDate
		*out = (*in).DeepCopy()
	}
	if in.IsEncrypted != nil {
		in, out := &in.IsEncrypted, &out.IsEncrypted
		*out = new(bool)
		**out = **in
	}
	if in.IsParent != nil {
		in, out := &in.IsParent, &out.IsParent
		*out = new(bool)
		**out = **in
	}
	if in.MessageCategory != nil {
		in, out := &in.MessageCategory, &out.MessageCategory
		*out = new(string)
		**out = **in
	}
	if in.ParentJobID != nil {
		in, out := &in.ParentJobID, &out.ParentJobID
		*out = new(string)
		**out = **in
	}
	if in.PercentDone != nil {
		in, out := &in.PercentDone, &out.PercentDone
		*out = new(string)
		**out = **in
	}
	if in.RecoveryPointARN != nil {
		in, out := &in.RecoveryPointARN, &out.RecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.RecoveryPointLifecycle != nil {
		in, out := &in.RecoveryPointLifecycle, &out.RecoveryPointLifecycle
		*out = new(Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.StartBy != nil {
		in, out := &in.StartBy, &out.StartBy
		*out = (*in).DeepCopy()
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
	if in.VaultLockState != nil {
		in, out := &in.VaultLockState, &out.VaultLockState
		*out = new(string)
		**out = **in
	}
	if in.VaultType != nil {
		in, out := &in.VaultType, &out.VaultType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Job.
func (in *Job) DeepCopy() *Job {
	if in == nil {
		return nil
	}
	out := new(Job)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatestMpaApprovalTeamUpdate) DeepCopyInto(out *LatestMpaApprovalTeamUpdate) {
	*out = *in
	if in.ExpiryDate != nil {
		in, out := &in.ExpiryDate, &out.ExpiryDate
		*out = (*in).DeepCopy()
	}
	if in.InitiationDate != nil {
		in, out := &in.InitiationDate, &out.InitiationDate
		*out = (*in).DeepCopy()
	}
	if in.MpaSessionARN != nil {
		in, out := &in.MpaSessionARN, &out.MpaSessionARN
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatestMpaApprovalTeamUpdate.
func (in *LatestMpaApprovalTeamUpdate) DeepCopy() *LatestMpaApprovalTeamUpdate {
	if in == nil {
		return nil
	}
	out := new(LatestMpaApprovalTeamUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatestRevokeRequest) DeepCopyInto(out *LatestRevokeRequest) {
	*out = *in
	if in.ExpiryDate != nil {
		in, out := &in.ExpiryDate, &out.ExpiryDate
		*out = (*in).DeepCopy()
	}
	if in.InitiationDate != nil {
		in, out := &in.InitiationDate, &out.InitiationDate
		*out = (*in).DeepCopy()
	}
	if in.MpaSessionARN != nil {
		in, out := &in.MpaSessionARN, &out.MpaSessionARN
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatestRevokeRequest.
func (in *LatestRevokeRequest) DeepCopy() *LatestRevokeRequest {
	if in == nil {
		return nil
	}
	out := new(LatestRevokeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegalHold) DeepCopyInto(out *LegalHold) {
	*out = *in
	if in.CancellationDate != nil {
		in, out := &in.CancellationDate, &out.CancellationDate
		*out = (*in).DeepCopy()
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LegalHoldARN != nil {
		in, out := &in.LegalHoldARN, &out.LegalHoldARN
		*out = new(string)
		**out = **in
	}
	if in.LegalHoldID != nil {
		in, out := &in.LegalHoldID, &out.LegalHoldID
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegalHold.
func (in *LegalHold) DeepCopy() *LegalHold {
	if in == nil {
		return nil
	}
	out := new(LegalHold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lifecycle) DeepCopyInto(out *Lifecycle) {
	*out = *in
	if in.DeleteAfterDays != nil {
		in, out := &in.DeleteAfterDays, &out.DeleteAfterDays
		*out = new(int64)
		**out = **in
	}
	if in.DeleteAfterEvent != nil {
		in, out := &in.DeleteAfterEvent, &out.DeleteAfterEvent
		*out = new(string)
		**out = **in
	}
	if in.MoveToColdStorageAfterDays != nil {
		in, out := &in.MoveToColdStorageAfterDays, &out.MoveToColdStorageAfterDays
		*out = new(int64)
		**out = **in
	}
	if in.OptInToArchiveForSupportedResources != nil {
		in, out := &in.OptInToArchiveForSupportedResources, &out.OptInToArchiveForSupportedResources
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lifecycle.
func (in *Lifecycle) DeepCopy() *Lifecycle {
	if in == nil {
		return nil
	}
	out := new(Lifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plan) DeepCopyInto(out *Plan) {
	*out = *in
	if in.AdvancedBackupSettings != nil {
		in, out := &in.AdvancedBackupSettings, &out.AdvancedBackupSettings
		*out = make([]*AdvancedBackupSetting, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AdvancedBackupSetting)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.BackupPlanName != nil {
		in, out := &in.BackupPlanName, &out.BackupPlanName
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]*Rule, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Rule)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ScanSettings != nil {
		in, out := &in.ScanSettings, &out.ScanSettings
		*out = make([]*ScanSetting, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ScanSetting)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plan.
func (in *Plan) DeepCopy() *Plan {
	if in == nil {
		return nil
	}
	out := new(Plan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanInput) DeepCopyInto(out *PlanInput) {
	*out = *in
	if in.AdvancedBackupSettings != nil {
		in, out := &in.AdvancedBackupSettings, &out.AdvancedBackupSettings
		*out = make([]*AdvancedBackupSetting, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AdvancedBackupSetting)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.BackupPlanName != nil {
		in, out := &in.BackupPlanName, &out.BackupPlanName
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]*RuleInput, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RuleInput)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ScanSettings != nil {
		in, out := &in.ScanSettings, &out.ScanSettings
		*out = make([]*ScanSetting, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ScanSetting)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanInput.
func (in *PlanInput) DeepCopy() *PlanInput {
	if in == nil {
		return nil
	}
	out := new(PlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanTemplatesListMember) DeepCopyInto(out *PlanTemplatesListMember) {
	*out = *in
	if in.BackupPlanTemplateID != nil {
		in, out := &in.BackupPlanTemplateID, &out.BackupPlanTemplateID
		*out = new(string)
		**out = **in
	}
	if in.BackupPlanTemplateName != nil {
		in, out := &in.BackupPlanTemplateName, &out.BackupPlanTemplateName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanTemplatesListMember.
func (in *PlanTemplatesListMember) DeepCopy() *PlanTemplatesListMember {
	if in == nil {
		return nil
	}
	out := new(PlanTemplatesListMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlansListMember) DeepCopyInto(out *PlansListMember) {
	*out = *in
	if in.AdvancedBackupSettings != nil {
		in, out := &in.AdvancedBackupSettings, &out.AdvancedBackupSettings
		*out = make([]*AdvancedBackupSetting, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AdvancedBackupSetting)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.BackupPlanARN != nil {
		in, out := &in.BackupPlanARN, &out.BackupPlanARN
		*out = new(string)
		**out = **in
	}
	if in.BackupPlanID != nil {
		in, out := &in.BackupPlanID, &out.BackupPlanID
		*out = new(string)
		**out = **in
	}
	if in.BackupPlanName != nil {
		in, out := &in.BackupPlanName, &out.BackupPlanName
		*out = new(string)
		**out = **in
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.CreatorRequestID != nil {
		in, out := &in.CreatorRequestID, &out.CreatorRequestID
		*out = new(string)
		**out = **in
	}
	if in.DeletionDate != nil {
		in, out := &in.DeletionDate, &out.DeletionDate
		*out = (*in).DeepCopy()
	}
	if in.LastExecutionDate != nil {
		in, out := &in.LastExecutionDate, &out.LastExecutionDate
		*out = (*in).DeepCopy()
	}
	if in.VersionID != nil {
		in, out := &in.VersionID, &out.VersionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlansListMember.
func (in *PlansListMember) DeepCopy() *PlansListMember {
	if in == nil {
		return nil
	}
	out := new(PlansListMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedResource) DeepCopyInto(out *ProtectedResource) {
	*out = *in
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.LastBackupVaultARN != nil {
		in, out := &in.LastBackupVaultARN, &out.LastBackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.LastRecoveryPointARN != nil {
		in, out := &in.LastRecoveryPointARN, &out.LastRecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedResource.
func (in *ProtectedResource) DeepCopy() *ProtectedResource {
	if in == nil {
		return nil
	}
	out := new(ProtectedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointByBackupVault) DeepCopyInto(out *RecoveryPointByBackupVault) {
	*out = *in
	if in.BackupSizeInBytes != nil {
		in, out := &in.BackupSizeInBytes, &out.BackupSizeInBytes
		*out = new(int64)
		**out = **in
	}
	if in.BackupVaultARN != nil {
		in, out := &in.BackupVaultARN, &out.BackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.BackupVaultName != nil {
		in, out := &in.BackupVaultName, &out.BackupVaultName
		*out = new(string)
		**out = **in
	}
	if in.CompletionDate != nil {
		in, out := &in.CompletionDate, &out.CompletionDate
		*out = (*in).DeepCopy()
	}
	if in.CompositeMemberIdentifier != nil {
		in, out := &in.CompositeMemberIdentifier, &out.CompositeMemberIdentifier
		*out = new(string)
		**out = **in
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyType != nil {
		in, out := &in.EncryptionKeyType, &out.EncryptionKeyType
		*out = new(string)
		**out = **in
	}
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
	if in.IndexStatusMessage != nil {
		in, out := &in.IndexStatusMessage, &out.IndexStatusMessage
		*out = new(string)
		**out = **in
	}
	if in.InitiationDate != nil {
		in, out := &in.InitiationDate, &out.InitiationDate
		*out = (*in).DeepCopy()
	}
	if in.IsEncrypted != nil {
		in, out := &in.IsEncrypted, &out.IsEncrypted
		*out = new(bool)
		**out = **in
	}
	if in.IsParent != nil {
		in, out := &in.IsParent, &out.IsParent
		*out = new(bool)
		**out = **in
	}
	if in.LastRestoreTime != nil {
		in, out := &in.LastRestoreTime, &out.LastRestoreTime
		*out = (*in).DeepCopy()
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	if in.ParentRecoveryPointARN != nil {
		in, out := &in.ParentRecoveryPointARN, &out.ParentRecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.RecoveryPointARN != nil {
		in, out := &in.RecoveryPointARN, &out.RecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.SourceBackupVaultARN != nil {
		in, out := &in.SourceBackupVaultARN, &out.SourceBackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
	if in.VaultType != nil {
		in, out := &in.VaultType, &out.VaultType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointByBackupVault.
func (in *RecoveryPointByBackupVault) DeepCopy() *RecoveryPointByBackupVault {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointByBackupVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointByResource) DeepCopyInto(out *RecoveryPointByResource) {
	*out = *in
	if in.BackupSizeBytes != nil {
		in, out := &in.BackupSizeBytes, &out.BackupSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.BackupVaultName != nil {
		in, out := &in.BackupVaultName, &out.BackupVaultName
		*out = new(string)
		**out = **in
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyType != nil {
		in, out := &in.EncryptionKeyType, &out.EncryptionKeyType
		*out = new(string)
		**out = **in
	}
	if in.IndexStatusMessage != nil {
		in, out := &in.IndexStatusMessage, &out.IndexStatusMessage
		*out = new(string)
		**out = **in
	}
	if in.IsParent != nil {
		in, out := &in.IsParent, &out.IsParent
		*out = new(bool)
		**out = **in
	}
	if in.ParentRecoveryPointARN != nil {
		in, out := &in.ParentRecoveryPointARN, &out.ParentRecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.RecoveryPointARN != nil {
		in, out := &in.RecoveryPointARN, &out.RecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
	if in.VaultType != nil {
		in, out := &in.VaultType, &out.VaultType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointByResource.
func (in *RecoveryPointByResource) DeepCopy() *RecoveryPointByResource {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointByResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointCreator) DeepCopyInto(out *RecoveryPointCreator) {
	*out = *in
	if in.BackupPlanARN != nil {
		in, out := &in.BackupPlanARN, &out.BackupPlanARN
		*out = new(string)
		**out = **in
	}
	if in.BackupPlanID != nil {
		in, out := &in.BackupPlanID, &out.BackupPlanID
		*out = new(string)
		**out = **in
	}
	if in.BackupPlanName != nil {
		in, out := &in.BackupPlanName, &out.BackupPlanName
		*out = new(string)
		**out = **in
	}
	if in.BackupPlanVersion != nil {
		in, out := &in.BackupPlanVersion, &out.BackupPlanVersion
		*out = new(string)
		**out = **in
	}
	if in.BackupRuleCron != nil {
		in, out := &in.BackupRuleCron, &out.BackupRuleCron
		*out = new(string)
		**out = **in
	}
	if in.BackupRuleID != nil {
		in, out := &in.BackupRuleID, &out.BackupRuleID
		*out = new(string)
		**out = **in
	}
	if in.BackupRuleName != nil {
		in, out := &in.BackupRuleName, &out.BackupRuleName
		*out = new(string)
		**out = **in
	}
	if in.BackupRuleTimezone != nil {
		in, out := &in.BackupRuleTimezone, &out.BackupRuleTimezone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointCreator.
func (in *RecoveryPointCreator) DeepCopy() *RecoveryPointCreator {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointCreator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointMember) DeepCopyInto(out *RecoveryPointMember) {
	*out = *in
	if in.BackupVaultName != nil {
		in, out := &in.BackupVaultName, &out.BackupVaultName
		*out = new(string)
		**out = **in
	}
	if in.RecoveryPointARN != nil {
		in, out := &in.RecoveryPointARN, &out.RecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointMember.
func (in *RecoveryPointMember) DeepCopy() *RecoveryPointMember {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportDeliveryChannel) DeepCopyInto(out *ReportDeliveryChannel) {
	*out = *in
	if in.S3BucketName != nil {
		in, out := &in.S3BucketName, &out.S3BucketName
		*out = new(string)
		**out = **in
	}
	if in.S3KeyPrefix != nil {
		in, out := &in.S3KeyPrefix, &out.S3KeyPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportDeliveryChannel.
func (in *ReportDeliveryChannel) DeepCopy() *ReportDeliveryChannel {
	if in == nil {
		return nil
	}
	out := new(ReportDeliveryChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportDestination) DeepCopyInto(out *ReportDestination) {
	*out = *in
	if in.S3BucketName != nil {
		in, out := &in.S3BucketName, &out.S3BucketName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportDestination.
func (in *ReportDestination) DeepCopy() *ReportDestination {
	if in == nil {
		return nil
	}
	out := new(ReportDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportJob) DeepCopyInto(out *ReportJob) {
	*out = *in
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.ReportPlanARN != nil {
		in, out := &in.ReportPlanARN, &out.ReportPlanARN
		*out = new(string)
		**out = **in
	}
	if in.ReportTemplate != nil {
		in, out := &in.ReportTemplate, &out.ReportTemplate
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportJob.
func (in *ReportJob) DeepCopy() *ReportJob {
	if in == nil {
		return nil
	}
	out := new(ReportJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportPlan) DeepCopyInto(out *ReportPlan) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.DeploymentStatus != nil {
		in, out := &in.DeploymentStatus, &out.DeploymentStatus
		*out = new(string)
		**out = **in
	}
	if in.LastAttemptedExecutionTime != nil {
		in, out := &in.LastAttemptedExecutionTime, &out.LastAttemptedExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulExecutionTime != nil {
		in, out := &in.LastSuccessfulExecutionTime, &out.LastSuccessfulExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.ReportPlanARN != nil {
		in, out := &in.ReportPlanARN, &out.ReportPlanARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportPlan.
func (in *ReportPlan) DeepCopy() *ReportPlan {
	if in == nil {
		return nil
	}
	out := new(ReportPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportSetting) DeepCopyInto(out *ReportSetting) {
	*out = *in
	if in.ReportTemplate != nil {
		in, out := &in.ReportTemplate, &out.ReportTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportSetting.
func (in *ReportSetting) DeepCopy() *ReportSetting {
	if in == nil {
		return nil
	}
	out := new(ReportSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelection) DeepCopyInto(out *ResourceSelection) {
	*out = *in
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelection.
func (in *ResourceSelection) DeepCopy() *ResourceSelection {
	if in == nil {
		return nil
	}
	out := new(ResourceSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreAccessBackupVaultListMember) DeepCopyInto(out *RestoreAccessBackupVaultListMember) {
	*out = *in
	if in.ApprovalDate != nil {
		in, out := &in.ApprovalDate, &out.ApprovalDate
		*out = (*in).DeepCopy()
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.RestoreAccessBackupVaultARN != nil {
		in, out := &in.RestoreAccessBackupVaultARN, &out.RestoreAccessBackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.VaultState != nil {
		in, out := &in.VaultState, &out.VaultState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreAccessBackupVaultListMember.
func (in *RestoreAccessBackupVaultListMember) DeepCopy() *RestoreAccessBackupVaultListMember {
	if in == nil {
		return nil
	}
	out := new(RestoreAccessBackupVaultListMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreJobCreator) DeepCopyInto(out *RestoreJobCreator) {
	*out = *in
	if in.RestoreTestingPlanARN != nil {
		in, out := &in.RestoreTestingPlanARN, &out.RestoreTestingPlanARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreJobCreator.
func (in *RestoreJobCreator) DeepCopy() *RestoreJobCreator {
	if in == nil {
		return nil
	}
	out := new(RestoreJobCreator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreJobSummary) DeepCopyInto(out *RestoreJobSummary) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreJobSummary.
func (in *RestoreJobSummary) DeepCopy() *RestoreJobSummary {
	if in == nil {
		return nil
	}
	out := new(RestoreJobSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreJobsListMember) DeepCopyInto(out *RestoreJobsListMember) {
	*out = *in
	if in.BackupSizeInBytes != nil {
		in, out := &in.BackupSizeInBytes, &out.BackupSizeInBytes
		*out = new(int64)
		**out = **in
	}
	if in.BackupVaultARN != nil {
		in, out := &in.BackupVaultARN, &out.BackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.CompletionDate != nil {
		in, out := &in.CompletionDate, &out.CompletionDate
		*out = (*in).DeepCopy()
	}
	if in.CreatedResourceARN != nil {
		in, out := &in.CreatedResourceARN, &out.CreatedResourceARN
		*out = new(string)
		**out = **in
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.DeletionStatusMessage != nil {
		in, out := &in.DeletionStatusMessage, &out.DeletionStatusMessage
		*out = new(string)
		**out = **in
	}
	if in.ExpectedCompletionTimeMinutes != nil {
		in, out := &in.ExpectedCompletionTimeMinutes, &out.ExpectedCompletionTimeMinutes
		*out = new(int64)
		**out = **in
	}
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
	if in.IsParent != nil {
		in, out := &in.IsParent, &out.IsParent
		*out = new(bool)
		**out = **in
	}
	if in.ParentJobID != nil {
		in, out := &in.ParentJobID, &out.ParentJobID
		*out = new(string)
		**out = **in
	}
	if in.PercentDone != nil {
		in, out := &in.PercentDone, &out.PercentDone
		*out = new(string)
		**out = **in
	}
	if in.RecoveryPointARN != nil {
		in, out := &in.RecoveryPointARN, &out.RecoveryPointARN
		*out = new(string)
		**out = **in
	}
	if in.RecoveryPointCreationDate != nil {
		in, out := &in.RecoveryPointCreationDate, &out.RecoveryPointCreationDate
		*out = (*in).DeepCopy()
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.RestoreJobID != nil {
		in, out := &in.RestoreJobID, &out.RestoreJobID
		*out = new(string)
		**out = **in
	}
	if in.SourceResourceARN != nil {
		in, out := &in.SourceResourceARN, &out.SourceResourceARN
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
	if in.ValidationStatusMessage != nil {
		in, out := &in.ValidationStatusMessage, &out.ValidationStatusMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreJobsListMember.
func (in *RestoreJobsListMember) DeepCopy() *RestoreJobsListMember {
	if in == nil {
		return nil
	}
	out := new(RestoreJobsListMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTestingPlanForGet) DeepCopyInto(out *RestoreTestingPlanForGet) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.LastExecutionTime != nil {
		in, out := &in.LastExecutionTime, &out.LastExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTestingPlanForGet.
func (in *RestoreTestingPlanForGet) DeepCopy() *RestoreTestingPlanForGet {
	if in == nil {
		return nil
	}
	out := new(RestoreTestingPlanForGet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTestingPlanForList) DeepCopyInto(out *RestoreTestingPlanForList) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.LastExecutionTime != nil {
		in, out := &in.LastExecutionTime, &out.LastExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTestingPlanForList.
func (in *RestoreTestingPlanForList) DeepCopy() *RestoreTestingPlanForList {
	if in == nil {
		return nil
	}
	out := new(RestoreTestingPlanForList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTestingSelectionForGet) DeepCopyInto(out *RestoreTestingSelectionForGet) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTestingSelectionForGet.
func (in *RestoreTestingSelectionForGet) DeepCopy() *RestoreTestingSelectionForGet {
	if in == nil {
		return nil
	}
	out := new(RestoreTestingSelectionForGet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTestingSelectionForList) DeepCopyInto(out *RestoreTestingSelectionForList) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTestingSelectionForList.
func (in *RestoreTestingSelectionForList) DeepCopy() *RestoreTestingSelectionForList {
	if in == nil {
		return nil
	}
	out := new(RestoreTestingSelectionForList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	if in.CompletionWindowMinutes != nil {
		in, out := &in.CompletionWindowMinutes, &out.CompletionWindowMinutes
		*out = new(int64)
		**out = **in
	}
	if in.CopyActions != nil {
		in, out := &in.CopyActions, &out.CopyActions
		*out = make([]*CopyAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CopyAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.EnableContinuousBackup != nil {
		in, out := &in.EnableContinuousBackup, &out.EnableContinuousBackup
		*out = new(bool)
		**out = **in
	}
	if in.IndexActions != nil {
		in, out := &in.IndexActions, &out.IndexActions
		*out = make([]*IndexAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IndexAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	if in.RecoveryPointTags != nil {
		in, out := &in.RecoveryPointTags, &out.RecoveryPointTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.RuleID != nil {
		in, out := &in.RuleID, &out.RuleID
		*out = new(string)
		**out = **in
	}
	if in.RuleName != nil {
		in, out := &in.RuleName, &out.RuleName
		*out = new(string)
		**out = **in
	}
	if in.ScanActions != nil {
		in, out := &in.ScanActions, &out.ScanActions
		*out = make([]*ScanAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ScanAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ScheduleExpression != nil {
		in, out := &in.ScheduleExpression, &out.ScheduleExpression
		*out = new(string)
		**out = **in
	}
	if in.ScheduleExpressionTimezone != nil {
		in, out := &in.ScheduleExpressionTimezone, &out.ScheduleExpressionTimezone
		*out = new(string)
		**out = **in
	}
	if in.StartWindowMinutes != nil {
		in, out := &in.StartWindowMinutes, &out.StartWindowMinutes
		*out = new(int64)
		**out = **in
	}
	if in.TargetBackupVaultName != nil {
		in, out := &in.TargetBackupVaultName, &out.TargetBackupVaultName
		*out = new(string)
		**out = **in
	}
	if in.TargetLogicallyAirGappedBackupVaultARN != nil {
		in, out := &in.TargetLogicallyAirGappedBackupVaultARN, &out.TargetLogicallyAirGappedBackupVaultARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleInput) DeepCopyInto(out *RuleInput) {
	*out = *in
	if in.CompletionWindowMinutes != nil {
		in, out := &in.CompletionWindowMinutes, &out.CompletionWindowMinutes
		*out = new(int64)
		**out = **in
	}
	if in.CopyActions != nil {
		in, out := &in.CopyActions, &out.CopyActions
		*out = make([]*CopyAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CopyAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.EnableContinuousBackup != nil {
		in, out := &in.EnableContinuousBackup, &out.EnableContinuousBackup
		*out = new(bool)
		**out = **in
	}
	if in.IndexActions != nil {
		in, out := &in.IndexActions, &out.IndexActions
		*out = make([]*IndexAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IndexAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	if in.RecoveryPointTags != nil {
		in, out := &in.RecoveryPointTags, &out.RecoveryPointTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.RuleName != nil {
		in, out := &in.RuleName, &out.RuleName
		*out = new(string)
		**out = **in
	}
	if in.ScanActions != nil {
		in, out := &in.ScanActions, &out.ScanActions
		*out = make([]*ScanAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ScanAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ScheduleExpression != nil {
		in, out := &in.ScheduleExpression, &out.ScheduleExpression
		*out = new(string)
		**out = **in
	}
	if in.ScheduleExpressionTimezone != nil {
		in, out := &in.ScheduleExpressionTimezone, &out.ScheduleExpressionTimezone
		*out = new(string)
		**out = **in
	}
	if in.StartWindowMinutes != nil {
		in, out := &in.StartWindowMinutes, &out.StartWindowMinutes
		*out = new(int64)
		**out = **in
	}
	if in.TargetBackupVaultName != nil {
		in, out := &in.TargetBackupVaultName, &out.TargetBackupVaultName
		*out = new(string)
		**out = **in
	}
	if in.TargetBackupVaultRef != nil {
		in, out := &in.TargetBackupVaultRef, &out.TargetBackupVaultRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetLogicallyAirGappedBackupVaultARN != nil {
		in, out := &in.TargetLogicallyAirGappedBackupVaultARN, &out.TargetLogicallyAirGappedBackupVaultARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleInput.
func (in *RuleInput) DeepCopy() *RuleInput {
	if in == nil {
		return nil
	}
	out := new(RuleInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanAction) DeepCopyInto(out *ScanAction) {
	*out = *in
	if in.MalwareScanner != nil {
		in, out := &in.MalwareScanner, &out.MalwareScanner
		*out = new(string)
		**out = **in
	}
	if in.ScanMode != nil {
		in, out := &in.ScanMode, &out.ScanMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanAction.
func (in *ScanAction) DeepCopy() *ScanAction {
	if in == nil {
		return nil
	}
	out := new(ScanAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanJob) DeepCopyInto(out *ScanJob) {
	*out = *in
	if in.CompletionDate != nil {
		in, out := &in.CompletionDate, &out.CompletionDate
		*out = (*in).DeepCopy()
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.MalwareScanner != nil {
		in, out := &in.MalwareScanner, &out.MalwareScanner
		*out = new(string)
		**out = **in
	}
	if in.ScanMode != nil {
		in, out := &in.ScanMode, &out.ScanMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanJob.
func (in *ScanJob) DeepCopy() *ScanJob {
	if in == nil {
		return nil
	}
	out := new(ScanJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanJobSummary) DeepCopyInto(out *ScanJobSummary) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.MalwareScanner != nil {
		in, out := &in.MalwareScanner, &out.MalwareScanner
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanJobSummary.
func (in *ScanJobSummary) DeepCopy() *ScanJobSummary {
	if in == nil {
		return nil
	}
	out := new(ScanJobSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanResult) DeepCopyInto(out *ScanResult) {
	*out = *in
	if in.LastScanTimestamp != nil {
		in, out := &in.LastScanTimestamp, &out.LastScanTimestamp
		*out = (*in).DeepCopy()
	}
	if in.MalwareScanner != nil {
		in, out := &in.MalwareScanner, &out.MalwareScanner
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanResult.
func (in *ScanResult) DeepCopy() *ScanResult {
	if in == nil {
		return nil
	}
	out := new(ScanResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanSetting) DeepCopyInto(out *ScanSetting) {
	*out = *in
	if in.MalwareScanner != nil {
		in, out := &in.MalwareScanner, &out.MalwareScanner
		*out = new(string)
		**out = **in
	}
	if in.ResourceTypes != nil {
		in, out := &in.ResourceTypes, &out.ResourceTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScannerRoleARN != nil {
		in, out := &in.ScannerRoleARN, &out.ScannerRoleARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanSetting.
func (in *ScanSetting) DeepCopy() *ScanSetting {
	if in == nil {
		return nil
	}
	out := new(ScanSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledPlanExecutionMember) DeepCopyInto(out *ScheduledPlanExecutionMember) {
	*out = *in
	if in.ExecutionTime != nil {
		in, out := &in.ExecutionTime, &out.ExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.RuleExecutionType != nil {
		in, out := &in.RuleExecutionType, &out.RuleExecutionType
		*out = new(string)
		**out = **in
	}
	if in.RuleID != nil {
		in, out := &in.RuleID, &out.RuleID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledPlanExecutionMember.
func (in *ScheduledPlanExecutionMember) DeepCopy() *ScheduledPlanExecutionMember {
	if in == nil {
		return nil
	}
	out := new(ScheduledPlanExecutionMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Selection) DeepCopyInto(out *Selection) {
	*out = *in
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Selection.
func (in *Selection) DeepCopy() *Selection {
	if in == nil {
		return nil
	}
	out := new(Selection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectionsListMember) DeepCopyInto(out *SelectionsListMember) {
	*out = *in
	if in.BackupPlanID != nil {
		in, out := &in.BackupPlanID, &out.BackupPlanID
		*out = new(string)
		**out = **in
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.CreatorRequestID != nil {
		in, out := &in.CreatorRequestID, &out.CreatorRequestID
		*out = new(string)
		**out = **in
	}
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
	if in.SelectionID != nil {
		in, out := &in.SelectionID, &out.SelectionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectionsListMember.
func (in *SelectionsListMember) DeepCopy() *SelectionsListMember {
	if in == nil {
		return nil
	}
	out := new(SelectionsListMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TieringConfiguration) DeepCopyInto(out *TieringConfiguration) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.TieringConfigurationARN != nil {
		in, out := &in.TieringConfigurationARN, &out.TieringConfigurationARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TieringConfiguration.
func (in *TieringConfiguration) DeepCopy() *TieringConfiguration {
	if in == nil {
		return nil
	}
	out := new(TieringConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TieringConfigurationsListMember) DeepCopyInto(out *TieringConfigurationsListMember) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.TieringConfigurationARN != nil {
		in, out := &in.TieringConfigurationARN, &out.TieringConfigurationARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TieringConfigurationsListMember.
func (in *TieringConfigurationsListMember) DeepCopy() *TieringConfigurationsListMember {
	if in == nil {
		return nil
	}
	out := new(TieringConfigurationsListMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultListMember) DeepCopyInto(out *VaultListMember) {
	*out = *in
	if in.BackupVaultARN != nil {
		in, out := &in.BackupVaultARN, &out.BackupVaultARN
		*out = new(string)
		**out = **in
	}
	if in.BackupVaultName != nil {
		in, out := &in.BackupVaultName, &out.BackupVaultName
		*out = new(string)
		**out = **in
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.CreatorRequestID != nil {
		in, out := &in.CreatorRequestID, &out.CreatorRequestID
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyType != nil {
		in, out := &in.EncryptionKeyType, &out.EncryptionKeyType
		*out = new(string)
		**out = **in
	}
	if in.LockDate != nil {
		in, out := &in.LockDate, &out.LockDate
		*out = (*in).DeepCopy()
	}
	if in.Locked != nil {
		in, out := &in.Locked, &out.Locked
		*out = new(bool)
		**out = **in
	}
	if in.MaxRetentionDays != nil {
		in, out := &in.MaxRetentionDays, &out.MaxRetentionDays
		*out = new(int64)
		**out = **in
	}
	if in.MinRetentionDays != nil {
		in, out := &in.MinRetentionDays, &out.MinRetentionDays
		*out = new(int64)
		**out = **in
	}
	if in.NumberOfRecoveryPoints != nil {
		in, out := &in.NumberOfRecoveryPoints, &out.NumberOfRecoveryPoints
		*out = new(int64)
		**out = **in
	}
	if in.VaultState != nil {
		in, out := &in.VaultState, &out.VaultState
		*out = new(string)
		**out = **in
	}
	if in.VaultType != nil {
		in, out := &in.VaultType, &out.VaultType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultListMember.
func (in *VaultListMember) DeepCopy() *VaultListMember {
	if in == nil {
		return nil
	}
	out := new(VaultListMember)
	in.DeepCopyInto(out)
	return out
}
